DROP VIEW VW_FHSLYE
GO
CREATE VIEW VW_FHSLYE
AS
SELECT YXERPFH_ID F_GUID,YXERPFH_SL F_SL,ISNULL(F_SPSL,0)F_SPSL,ISNULL(F_ZTSL,0)F_ZTSL, ISNULL(F_SPSL,0)+ISNULL(F_ZTSL,0) F_SYSL,  YXERPFH_SL-ISNULL(F_SPSL,0)-ISNULL(F_ZTSL,0)  F_KYSL FROM YXERPFH LEFT JOIN

(
 SELECT YXTHSQMX_GUID F_ID,SUM(YXTHSQMX_THSL)F_SPSL FROM  YXTHSQ, YXTHSQMX WHERE YXTHSQ_LSBH=YXTHSQMX_LSBH AND YXTHSQ_SHBZ='1' 
 GROUP BY YXTHSQMX_GUID
) THSP ON YXERPFH_ID=THSP.F_ID
LEFT JOIN 
(
 SELECT YXTHSQMX_GUID F_ID,SUM(YXTHSQMX_THSL)F_ZTSL FROM  YXTHSQ, YXTHSQMX WHERE YXTHSQ_LSBH=YXTHSQMX_LSBH AND YXTHSQ_SHBZ!='1' 
 GROUP BY YXTHSQMX_GUID
) THZT ON YXERPFH_ID=THZT.F_ID

GO  
go

