--退货单申请保存后存储过程
DROP PROC SP_SD_THSQ_AFTERSAVE
GO
CREATE PROC SP_SD_THSQ_AFTERSAVE
(
@USERID VARCHAR(100), /*操作员ID*/ 
@BILLNO VARCHAR(40) /*单据流水号*/ 
)
AS
BEGIN
/*
 作者：陈洪磊
 日期：20191105
 功能：退货申请单保存后存储过程
*/
DECLARE @CON INT

--SELECT * FROM YXTHSQMX LEFT JOIN VW_FHSLYE ON F_ID=YXTHSQMX_ID WHERE YXTHSQMX_LSBH=@BILLNO

SELECT @CON=COUNT(*) FROM VW_FHSLYE,(SELECT YXTHSQMX_GUID FROM YXTHSQMX WHERE YXTHSQMX_LSBH=@BILLNO)LSB WHERE F_GUID=YXTHSQMX_GUID AND  F_KYSL<0
BEGIN
IF @CON>0
BEGIN      
      RAISERROR ('本次退货数量不能大于可退货数量',18,1) 
END
END


END

go



DROP  proc [SP_SDB_YXGFSQR_SAVE]
GO

CREATE proc SP_SDB_YXGFSQR_SAVE
(   
 @UserID varchar(40),   
 @BillNo varchar(40)    
)   
as 
/*授权委托书保存后存储过程*/
begin

	UPDATE YXGFSQR SET YXGFSQR_FJ1=YXSQS_SFZFJ,YXGFSQR_FJ2=YXSQS_BYZFJ,YXGFSQR_FJ3=YXSQS_XWZFJ  FROM (SELECT YXSQS_LSBH F_LSBH,  YXSQS_SFZFJ,YXSQS_BYZFJ,YXSQS_XWZFJ FROM YXSQS WHERE YXSQS_LSBH=(SELECT YXGFSQR_SQSID FROM YXGFSQR WHERE YXGFSQR_LSBH=@BillNo )) LSB WHERE F_LSBH=YXGFSQR_SQSID AND YXGFSQR_LSBH=@BillNo

	UPDATE YXSQS SET YXSQS_SFWC='1' WHERE YXSQS_LSBH=(SELECT YXGFSQR_SQSID FROM YXGFSQR WHERE YXGFSQR_LSBH=@BillNo )

end
GO


DROP PROC [SP_DRP_SDB_FHJH_GETDJPL] 
GO
CREATE PROC [SP_DRP_SDB_FHJH_GETDJPL] 
	@StrXML XML ,--产品单价XML串
	@KH   VARCHAR(40),--客户内码
	@NY  VARCHAR(6)--年月
AS 
/*############################################ 
获取发货计划表体的内容
作者陈洪磊 
创建时间2019年10月28日 
##############################################*/    
BEGIN 
	DECLARE @idoc int      
	DECLARE @Message varchar(200)   
    
	
	/*创建临时表*/   
	CREATE TABLE #TEMPRETURN   
	(   
		F_WLBH varchar(40),--协议对应产品
		F_JG DECIMAL(20,2),--单价
        F_YJFHSL DECIMAL(20,2),--月平均发货数量
        F_YJLXSL DECIMAL(20,2),--月平均流向销售数量
		F_SYKCSL DECIMAL(20,2),--商业库存数量
		F_FDBL DECIMAL(20,2),--浮动比率
		F_SYKCJE DECIMAL(20,2),--商业库存金额
		F_JHFHSL DECIMAL(20,2),--计划发货数量
		F_JHFHJE DECIMAL(20,2),--计划发货金额
		F_BYYFSL DECIMAL(20,2),--本月已发货数量
	)   
	CREATE TABLE #TEMP
	(
		F_PZ varchar(40),--协议对应产品
		F_DJ DECIMAL(20,2),--单价
	)
	
	--相关发货
 CREATE TABLE #TEMP1
 	(   
		F_PZ varchar(40),--协议对应产品
        F_SL DECIMAL(20,2),--月平均发货数量
	)  

	
	--相关流向
    CREATE TABLE #TEMP2
 	(   
		F_PZ varchar(40),--协议对应产品
        F_SL DECIMAL(20,2),--月平均流向销售数量
	)  

		--商业库存数量
    CREATE TABLE #TEMP3
 	(   
		F_PZ varchar(40),--产品
        F_SL DECIMAL(20,2),--商业库存数量
	)  
	
	--本月已发货数量
	 CREATE TABLE #TEMP4
 	(   
		F_PZ varchar(40),--产品
        F_BYSL DECIMAL(20,2),--本月数量
        F_LJSL DECIMAL(20,2),--
	) 
	--本月累计发货
	--本月累计发货完成率

	/*先获取页面上的产品*/   
	EXEC sp_xml_preparedocument @idoc OUTPUT, @StrXML   
	INSERT INTO #TEMP 
			(
				F_PZ,
				F_DJ
			)   
	SELECT	F_PZ,F_DJ
	FROM OPENXML (@idoc, '/ROOT/ITEM/F',1)   
	WITH (	
			F_PZ varchar(40),
			F_DJ DECIMAL(20,2)--单价
		 )   

	--获取发货数据明细
	--假如今天是10月份，应该取9、8、7月
	INSERT INTO #TEMP1(F_PZ,F_SL)
	SELECT F_PZ,ISNULL(SUM(YXERPFH_SL),0)/3 F_SL  FROM YXERPFH ,YXWLZD,#TEMP  
	WHERE YXERPFH_YXCPBH=YXWLZD_NM 
	AND YXWLZD_C05=F_PZ
	AND YXERPFH_KH=@KH
	AND LEFT(YXERPFH_YWRQ,6) BETWEEN Convert( VARCHAR(6), DATEADD(month, -3, getdate()) ,112) AND Convert( VARCHAR(6), DATEADD(month, -1, getdate()) ,112)
	GROUP BY F_PZ

	--获取流向数据明细
	INSERT INTO #TEMP2(F_PZ,F_SL)
	SELECT F_PZ,ISNULL(SUM(YXLXDMX_SL),0)/3 F_SL   FROM YXLXD,YXLXDMX ,#TEMP,(select YXWLZD_C06 F_CPPG,YXWLZD_C05 F_XYCP from YXWLZD where YXWLZD_C06 is not null and YXWLZD_C06<>'' group by YXWLZD_C06,YXWLZD_C05) C06  
	WHERE YXLXD_LSBH=YXLXDMX_LSBH 
	AND YXLXD_KH=@KH
	AND  YXLXDMX_WLMC=F_CPPG 
	AND F_XYCP=F_PZ  
	AND LEFT(YXLXDMX_XSRQ,6)  BETWEEN Convert( VARCHAR(6), DATEADD(month, -3, getdate()) ,112) AND Convert( VARCHAR(6), DATEADD(month, -1, getdate()) ,112)
	GROUP BY F_PZ

	 --获取商业库存数量,理论应该就一条，因为维度为 日期-客户-产品
	INSERT INTO #TEMP3(F_PZ,F_SL)
	SELECT YXQDJHDMX_WLBH,ISNULL(SUM(YXQDJHDMX_KCYE),0)/3 F_SL FROM  YXQDJHD,YXQDJHDMX,#TEMP,(select YXWLZD_C06 F_CPPG,YXWLZD_C05 F_XYCP from YXWLZD where YXWLZD_C06 is not null and YXWLZD_C06<>'' group by YXWLZD_C06,YXWLZD_C05)C06 
	WHERE YXQDJHD_LSBH=YXQDJHDMX_LSBH 
	and Convert( VARCHAR(6),EOMONTH (GETDATE(), -1),112)=YXQDJHD_TJNY 
	AND YXQDJHDMX_WLMC=F_CPPG 
	AND F_XYCP=F_PZ 
	AND YXQDJHDMX_KH=@KH 
    GROUP BY YXQDJHDMX_WLBH

	--获取本月发货数量
	INSERT INTO #TEMP4(F_PZ,F_BYSL)
	SELECT F_PZ,ISNULL(SUM(YXERPFH_SL),0) F_SL  FROM YXERPFH ,YXWLZD,#TEMP  
	WHERE YXERPFH_YXCPBH=YXWLZD_NM 
	AND YXWLZD_C05=F_PZ
	AND YXERPFH_KH=@KH
	AND LEFT(YXERPFH_YWRQ,6) =Convert( VARCHAR(6),getdate() ,112)
	GROUP BY F_PZ


--形成临时表的数据 品种、月平均发货数量、月平均流向销售数量、本月已发货数量
INSERT INTO #TEMPRETURN(F_WLBH,F_YJFHSL,F_YJLXSL,F_SYKCSL,F_BYYFSL)
SELECT F_PZ, SUM(F_SL1)F_SL1, SUM(F_SL2)F_SL2, SUM(F_SL3)F_SL3, SUM(F_SL4)F_SL4
FROM (
SELECT F_PZ ,F_SL F_SL1,0 F_SL2, 0 F_SL3, 0 F_SL4 FROM #TEMP1
UNION ALL
SELECT F_PZ ,0 F_SL1,F_SL F_SL2, 0 F_SL3, 0 F_SL4 FROM #TEMP2
UNION ALL
SELECT F_PZ ,0 F_SL1,0 F_SL2, F_SL F_SL3, 0 F_SL4 FROM #TEMP3
UNION ALL
SELECT F_PZ ,0 F_SL1,0 F_SL2, 0 F_SL3, F_BYSL F_SL4 FROM #TEMP4
) LSB GROUP BY F_PZ
--处理商业库存金额、计划发货数量、计划发货金额、浮动比例
UPDATE #TEMPRETURN SET F_JG=F_DJ, F_SYKCJE=F_SYKCSL*F_DJ,F_JHFHSL=F_YJLXSL*2-F_SYKCSL,F_JHFHJE=F_DJ*(F_YJLXSL*2-F_SYKCSL),F_FDBL=CASE WHEN F_YJFHSL=0 THEN 0 ELSE ((F_YJLXSL*2-F_SYKCSL)-F_YJFHSL)*100/F_YJFHSL END FROM #TEMP WHERE F_PZ=F_WLBH
     
SELECT 		F_PZ F_WLBH ,F_DJ F_JG, ISNULL(F_YJFHSL,0)F_YJFHSL , ISNULL(F_YJLXSL,0)F_YJLXSL,ISNULL(F_SYKCSL,0)F_SYKCSL,ISNULL(F_FDBL,0)F_FDBL,ISNULL(F_SYKCJE,0) F_SYKCJE, ISNULL(F_JHFHSL,0)F_JHFHSL,ISNULL(F_JHFHJE,0)F_JHFHJE,ISNULL(F_BYYFSL,0)F_BYYFSL FROM #TEMP LEFT JOIN  #TEMPRETURN ON F_PZ=F_WLBH
		

	--DROP TABLE TEMP
	
	IF @@ERROR < 0  GOTO ErrorHandler     
		RETURN 0   
	ErrorHandler:   
		RETURN @@ERROR    
   
 
END
GO


 DROP proc [SP_SDB_JJBC_SAVE]
 GO

CREATE proc [SP_SDB_JJBC_SAVE]
(   
 @UserID varchar(40),   
 @BillNo varchar(40)    
)   
as 
/*降价补差，保存后调用存储过程*/
begin
DECLARE @ZRFS VARCHAR(10)--1票折、2红冲
SELECT @ZRFS=YXJJBC_ZRFS FROM  YXJJBC WHERE YXJJBC_LSBH=@BillNo

--如果历史没有进行过降价补差
DECLARE @CON INT 
SELECT @CON=COUNT(*) FROM YXJJBCMX WHERE YXJJBCMX_LSBH=@BillNo AND YXJJBCMX_MINSL=0 AND YXJJBCMX_SXSL=0 AND YXJJBCMX_KCSL>YXJJBCMX_CKSL
IF @CON>0
BEGIN 
	RAISERROR ( '库存数量不能大于出库数量！', 16, 1)
	RETURN
END 
--如果历史进行过降价补差，且选择的类型为一次降价或者多次降价,库存数量都不能大于【出库数量-历史库存数量合计】
SELECT @CON=COUNT(*) FROM YXJJBCMX WHERE YXJJBCMX_LSBH=@BillNo AND  YXJJBCMX_SXSL!=0 AND YXJJBCMX_KCSL>(YXJJBCMX_CKSL-YXJJBCMX_SXSL) AND YXJJBCMX_JJLX=1
IF @CON>0
BEGIN 
	RAISERROR ( '库存数量不能大于[出库数量-历史库存数量合计]！', 16, 1)
	RETURN
END 

--如果历史进行过降价补差，且选择的类型为多次降价,库存数量不能大于历史最小库存数量
SELECT @CON=COUNT(*) FROM YXJJBCMX WHERE YXJJBCMX_LSBH=@BillNo AND  YXJJBCMX_SXSL!=0 and YXJJBCMX_MINSL!=0 AND YXJJBCMX_KCSL>YXJJBCMX_MINSL AND YXJJBCMX_JJLX=2
IF @CON>0
BEGIN 
	RAISERROR ( '【多次降价】库存数量不能大于【历史最小库存数量】！', 16, 1)
	RETURN
END 


--如果选择一次降价，如果渠道类型为15商务，销售单价等于原中标价，如果不是15,3里面的销售单价应该等于4里的原发货价。
SELECT @CON=COUNT(*) FROM YXJJBCMX WHERE YXJJBCMX_LSBH=@BillNo  AND YXJJBCMX_JJLX=1 and YXJJBCMX_QDLX='15' AND CAST(YXJJBCMX_XSDJ AS decimal(20,2))!=CAST(YXJJBCMX_YZBJ AS decimal(20,2))
IF @CON>0
BEGIN 
	RAISERROR ( '【渠道类型为商务】销售单价应该等于原中标价！', 16, 1)
	RETURN
END 

SELECT @CON=COUNT(*) FROM YXJJBCMX WHERE YXJJBCMX_LSBH=@BillNo  AND YXJJBCMX_JJLX=1 and YXJJBCMX_QDLX!='15' AND CAST(YXJJBCMX_XSDJ AS decimal(20,2)) !=CAST(YXJJBCMX_YFHJ AS decimal(20,2))
IF @CON>0
BEGIN 
	RAISERROR ( '【渠道类型不是商务】销售单价应该等于原发货价！', 16, 1)
	RETURN
END 




--处理降价补差金额
IF @ZRFS='1'--票折 需要减去配送费
BEGIN
UPDATE YXJJBCMX SET YXJJBCMX_ZRCHJE=YXJJBCMX_KCSL*YXJJBCMX_BCCH-YXJJBCMX_KHPSJE WHERE  YXJJBCMX_LSBH=@BillNo
END
ELSE IF @ZRFS='2'--红冲 
BEGIN
UPDATE YXJJBCMX SET YXJJBCMX_ZRCHJE=YXJJBCMX_KCSL*YXJJBCMX_BCCH WHERE  YXJJBCMX_LSBH=@BillNo
END


	
--生成表三的数据
CREATE TABLE #MXGUID
(
F_GUID VARCHAR(40)
)
INSERT INTO #MXGUID(F_GUID)
SELECT YXJJBCMX_GUID FROM YXJJBCMX WHERE YXJJBCMX_LSBH=@BillNo
--因为修改保存，把历史数据先清空
DELETE YXJJBCLS WHERE YXJJBCLS_LSBH=@BillNo
INSERT INTO YXJJBCLS (YXJJBCLS_LSBH,YXJJBCLS_FLBH, YXJJBCLS_GSID, YXJJBCLS_QDLX, YXJJBCLS_BMBH, YXJJBCLS_CRMDDRQ, YXJJBCLS_SAPTDH, YXJJBCLS_JSKPH, YXJJBCLS_PC, YXJJBCLS_WLBH, YXJJBCLS_GG, YXJJBCLS_JLDW, YXJJBCLS_CKSL, YXJJBCLS_ZKDJ, YXJJBCLS_FPSL, YXJJBCLS_YFHKL, YXJJBCLS_YZBJ, YXJJBCLS_YFHJ, YXJJBCLS_XZBJ, YXJJBCLS_XFHJ, YXJJBCLS_BCCH, YXJJBCLS_KCLX, YXJJBCLS_KCSL, YXJJBCLS_ZRCHJE, YXJJBCLS_JJSJ, YXJJBCLS_SYB, YXJJBCLS_KHPSJE, YXJJBCLS_KCJZRQ, YXJJBCLS_ZBBZ, YXJJBCLS_SWBZ, YXJJBCLS_CWBZ, YXJJBCLS_GUID,YXJJBCLS_LSDJBH, YXJJBCLS_XSDJ, YXJJBCLS_JJLX,YXJJBCLS_ZRZT)

SELECT 
@BillNo, RIGHT('0000'+CAST(ROW_NUMBER() OVER(ORDER BY YXJJBCMX_WLBH DESC ) AS VARCHAR),4), YXJJBCMX_GSID, YXJJBCMX_QDLX, YXJJBCMX_BMBH, YXJJBCMX_CRMDDRQ, YXJJBCMX_SAPTDH, YXJJBCMX_JSKPH, YXJJBCMX_PC, YXJJBCMX_WLBH, YXJJBCMX_GG, YXJJBCMX_JLDW, YXJJBCMX_CKSL, YXJJBCMX_ZKDJ, YXJJBCMX_FPSL, YXJJBCMX_YFHKL, YXJJBCMX_YZBJ, YXJJBCMX_YFHJ, YXJJBCMX_XZBJ, YXJJBCMX_XFHJ, YXJJBCMX_BCCH, YXJJBCMX_KCLX, YXJJBCMX_KCSL, YXJJBCMX_ZRCHJE, YXJJBCMX_JJSJ, YXJJBCMX_SYB, YXJJBCMX_KHPSJE, YXJJBCMX_KCJZRQ, YXJJBCMX_ZBBZ, YXJJBCMX_SWBZ, YXJJBCMX_CWBZ, YXJJBCMX_GUID,YXJJBC_DJBH, YXJJBCMX_XSDJ, YXJJBCMX_JJLX,YXJJBCMX_ZRZT FROM YXJJBC,YXJJBCMX,#MXGUID WHERE YXJJBC_LSBH=YXJJBCMX_LSBH AND YXJJBCMX_GUID=F_GUID AND YXJJBCMX_LSBH!=@BillNo

--处理表一

DELETE YXJJBCHZ WHERE YXJJBCHZ_LSBH=@BillNo

INSERT INTO YXJJBCHZ(YXJJBCHZ_LSBH,YXJJBCHZ_FLBH,YXJJBCHZ_GSID,YXJJBCHZ_QDLX,YXJJBCHZ_BMBH,YXJJBCHZ_FPSL,YXJJBCHZ_KCLX,YXJJBCHZ_SYB,YXJJBCHZ_ZRZT,YXJJBCHZ_JE)

SELECT  @BillNo, RIGHT('0000'+CAST(ROW_NUMBER() OVER(ORDER BY YXJJBCMX_GSID DESC ) AS VARCHAR),4) F_FLBH, YXJJBCMX_GSID, YXJJBCMX_QDLX, YXJJBCMX_BMBH,  YXJJBCMX_FPSL, YXJJBCMX_KCLX, YXJJBCMX_SYB,YXJJBCMX_ZRZT, YXJJBCMX_ZRCHJE   FROM (SELECT   YXJJBCMX_GSID, YXJJBCMX_QDLX, YXJJBCMX_BMBH,  YXJJBCMX_FPSL, YXJJBCMX_KCLX, YXJJBCMX_SYB,YXJJBCMX_ZRZT,SUM(YXJJBCMX_ZRCHJE) YXJJBCMX_ZRCHJE FROM YXJJBCMX
WHERE YXJJBCMX_LSBH=@BillNo
GROUP BY  YXJJBCMX_GSID, YXJJBCMX_QDLX, YXJJBCMX_BMBH,  YXJJBCMX_FPSL, YXJJBCMX_KCLX, YXJJBCMX_SYB,YXJJBCMX_ZRZT 
)LSB


--处理表头合计
DECLARE @JE DECIMAL(20,2)
SELECT @JE=ISNULL(SUM(YXJJBCMX_ZRCHJE),0) FROM YXJJBCMX WHERE  YXJJBCMX_LSBH=@BillNo

UPDATE YXJJBC SET YXJJBC_SQJE=@JE,YXJJBC_SHJE=@JE WHERE YXJJBC_LSBH=@BillNo



end

GO




 DROP proc SP_SDB_FHJH_SAVE
 GO
CREATE proc SP_SDB_FHJH_SAVE
(   
 @UserID varchar(40),   
 @BillNo varchar(40)    
)   
as 
/*发货计划，保存后调用存储过程*/
begin
DECLARE @CON INT 

SELECT @CON=COUNT(*) FROM YXXSHJMX WHERE YXXSHJMX_LSBH=@BillNo  AND ABS(YXXSHJMX_FDBL)>20 AND ISNULL(YXXSHJMX_ZJLSM,'')=''
IF @CON>0
BEGIN 
	RAISERROR ('【浮动比例上下浮动超过20】,请填写【增减量说明】', 16, 1)
	RETURN
END 



end
GO


DROP proc SP_SDB_JGZCSG_SAVE

GO
CREATE proc SP_SDB_JGZCSG_SAVE
(   
 @UserID varchar(40),   
 @BillNo varchar(40)    
)   
as 
/*手工的价格政策保存后存储过程*/
begin

--删除价格政策表相关的手工生成的数据(已在保存前存储过程处理了)
--DELETE YXJGZCB FROM  YXJGZCBMX WHERE YXJGZCBMX_ID=@BillNo AND YXJGZCB_ID=YXJGZCBMX_GUID AND YXJGZCB_LY='4'

--SELECT * FROM YXJGZCB  WHERE YXJGZCB_LY='4'
--先把当前单据的流水号的唯一标识更新上
UPDATE YXJGZCBMX SET YXJGZCBMX_GUID=NEWID() WHERE YXJGZCBMX_ID=@BillNo

--插入最新的

--唯一标识、部门（区域）、客户、物料、开票价
--低价、开始日期、结束日期、销量底线、来源类型
--使用标志、核算单位、通用名、商品名、规格、
--计量单位、制单日期、制单人、政策类型、是否判断
--备注、渠道类型、参考价二
INSERT INTO YXJGZCB(YXJGZCB_ID,YXJGZCB_SYB,YXJGZCB_BM,YXJGZCB_KHBH,YXJGZCB_WLBH,YXJGZCB_KPJ, 
                    YXJGZCB_DJ,YXJGZCB_KSRQ,YXJGZCB_JSRQ,YXJGZCB_XLDX,YXJGZCB_LY,
                    YXJGZCB_SYBZ,YXJGZCB_GSID,YXJGZCB_UF_TYM,YXJGZCB_UF_SPM,YXJGZCB_UF_GG,
					YXJGZCB_UF_JLDW,YXJGZCB_UF_ZDRQ,YXJGZCB_UF_ZDR,YXJGZCB_UF_ZCLX,YXJGZCB_UF_SFPD,
					YXJGZCB_DEMO,YXJGZCB_UFQDLX,YXJGZCB_UFKPJ2)

SELECT YXJGZCBMX_GUID F_ID,YXJGZCBM_SYB F_SYB,YXJGZCBM_BM F_BM,YXJGZCBM_KHBH F_KHBH,YXJGZCBMX_WLBH F_WLBH,YXJGZCBMX_KPJ F_KPJ,
        YXJGZCBMX_DJ F_DJ,YXJGZCBMX_KSRQ F_KSRQ,YXJGZCBMX_JSRQ F_JSRQ,YXJGZCBMX_XLDX F_XLDX,'4' F_LY,
		YXJGZCBMX_SYBZ F_SYBZ,YXJGZCBM_GSID F_GSID,YXJGZCBMX_UF_TYM F_TYM,YXJGZCBMX_UF_SPM F_SPM,YXJGZCBMX_UF_GG F_GG,
		YXJGZCBMX_UF_JLDW F_JLDW,YXJGZCBM_ZDRQ F_ZDRQ,YXJGZCBM_ZDR F_ZDR,YXJGZCBM_ZCLX F_ZCLX,YXJGZCBMX_UF_SFPD F_SFPD,
		YXJGZCBMX_DEMO F_BZ,YXJGZCBM_QDLX F_QDLX,YXJGZCBMX_UFKPJ2 F_CKJ2
 FROM YXJGZCBM,YXJGZCBMX WHERE YXJGZCBM_ID=YXJGZCBMX_ID AND YXJGZCBM_ID=@BillNo 






end
GO




DROP proc SP_SDB_JGZCSG_DR

GO
CREATE proc SP_SDB_JGZCSG_DR
(    
 @DRID varchar(40)    
)   
as 
/*手工的价格政策导入后存储过程*/
begin

--先把当前单据的流水号的唯一标识更新上
UPDATE YXJGZCBMX SET YXJGZCBMX_GUID=NEWID(),YXJGZCBMX_LY='4'  FROM YXJGZCBM  WHERE YXJGZCBM_ID=YXJGZCBMX_ID AND  YXJGZCBM_DRBS=@DRID

UPDATE YXJGZCBMX SET YXJGZCBMX_UF_TYM=YXWLZD_TYM ,YXJGZCBMX_UF_SPM=YXWLZD_SPM ,YXJGZCBMX_UF_GG=YXWLZD_GGXH ,	YXJGZCBMX_UF_JLDW=YXWLZD_JLDW FROM YXWLZD WHERE YXWLZD_NM=YXJGZCBMX_WLBH

--插入最新的

--唯一标识、部门（区域）、客户、物料、开票价
--低价、开始日期、结束日期、销量底线、来源类型
--使用标志、核算单位、通用名、商品名、规格、
--计量单位、制单日期、制单人、政策类型、是否判断
--备注、渠道类型、参考价二
INSERT INTO YXJGZCB(YXJGZCB_ID,YXJGZCB_SYB,YXJGZCB_BM,YXJGZCB_KHBH,YXJGZCB_WLBH,YXJGZCB_KPJ, 
                    YXJGZCB_DJ,YXJGZCB_KSRQ,YXJGZCB_JSRQ,YXJGZCB_XLDX,YXJGZCB_LY,
                    YXJGZCB_SYBZ,YXJGZCB_GSID,YXJGZCB_UF_TYM,YXJGZCB_UF_SPM,YXJGZCB_UF_GG,
					YXJGZCB_UF_JLDW,YXJGZCB_UF_ZDRQ,YXJGZCB_UF_ZDR,YXJGZCB_UF_ZCLX,YXJGZCB_UF_SFPD,
					YXJGZCB_DEMO,YXJGZCB_UFQDLX,YXJGZCB_UFKPJ2)

SELECT YXJGZCBMX_GUID F_ID,YXJGZCBM_SYB F_SYB,YXJGZCBM_BM F_BM,YXJGZCBM_KHBH F_KHBH,YXJGZCBMX_WLBH F_WLBH,YXJGZCBMX_KPJ F_KPJ,
        YXJGZCBMX_DJ F_DJ,YXJGZCBMX_KSRQ F_KSRQ,YXJGZCBMX_JSRQ F_JSRQ,YXJGZCBMX_XLDX F_XLDX,'4' F_LY,
		YXJGZCBMX_SYBZ F_SYBZ,YXJGZCBM_GSID F_GSID,YXJGZCBMX_UF_TYM F_TYM,YXJGZCBMX_UF_SPM F_SPM,YXJGZCBMX_UF_GG F_GG,
		YXJGZCBMX_UF_JLDW F_JLDW,YXJGZCBM_ZDRQ F_ZDRQ,YXJGZCBM_ZDR F_ZDR,YXJGZCBM_ZCLX F_ZCLX,YXJGZCBMX_UF_SFPD F_SFPD,
		YXJGZCBMX_DEMO F_BZ,YXJGZCBM_QDLX F_QDLX,YXJGZCBMX_UFKPJ2 F_CKJ2
 FROM YXJGZCBM,YXJGZCBMX WHERE YXJGZCBM_ID=YXJGZCBMX_ID AND  YXJGZCBM_DRBS=@DRID






end
GO
DROP PROC SP_SDB_KHXXBB_90001

GO

CREATE PROC [SP_SDB_KHXXBB_90001]
(
@GSID VARCHAR(40),
@KH   VARCHAR(40),
@DQ   VARCHAR(40),
@USERID varchar(40)
)
AS 
BEGIN

    DECLARE @filterSql varchar(4000) ---过滤串
	DECLARE @CON INT
--EXEC  SP_SDB_KHXXBB_90001 '','','',''
--客户信息报表
-- 核算单位,部门内码、客户内码,客户名称、曾用名1、曾用名2、地区、所在城市
--合作事业部、齐鲁经办人、企业属性、经营性质、客户等级
--仓库地址、客户邮编、注册资金、开户银行、账号
--税号、是否备案、协议回款周期、回款方式、(商业固定配送费用)
--(商业考核配送费用)、(调拨费用)、职务、姓名、性别、
--年龄、生日、电话、qq、微信、
--办公地址、爱好
CREATE TABLE #TEMP
(
F_GSID VARCHAR(40),
F_BMNM VARCHAR(40),
F_KHNM VARCHAR(40),
F_KHMC VARCHAR(200),
F_CYM1 VARCHAR(40),
F_CYM2 VARCHAR(40),
F_DQMC VARCHAR(40),
F_SZCS VARCHAR(40),
F_HZSYB VARCHAR(40),
F_QLJBR VARCHAR(40),
F_QYSX VARCHAR(40),
F_JYXZ VARCHAR(40),
F_KHDJ VARCHAR(40),
F_CKDZ VARCHAR(40),
F_KHYB VARCHAR(40),
F_ZCZJ VARCHAR(40),
F_KHYH VARCHAR(40),
F_ZH VARCHAR(40),
F_SH VARCHAR(40),
F_SFBA VARCHAR(40),
F_HKZQ VARCHAR(40),
F_HKFS VARCHAR(40),
F_PSFY FLOAT,
F_KHFY FLOAT,
F_DBFY FLOAT,
F_ZW VARCHAR(40),
F_XM VARCHAR(40),
F_XB VARCHAR(40),
F_NL VARCHAR(40),
F_SR VARCHAR(40),
F_DH VARCHAR(40),
F_QQ VARCHAR(40),
F_WX VARCHAR(40),
F_BGDZ VARCHAR(40),
F_AH VARCHAR(40)
)


CREATE TABLE #KHTABLE
(
F_KH VARCHAR(40)
)

SELECT @CON=COUNT(*) FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH AND YXCZYKH_CZY=@USERID
--操作员和客户关系表有数据
IF @CON>0
BEGIN

INSERT INTO #KHTABLE(F_KH)
SELECT YXCZYKHMX_KH FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH AND YXCZYKH_CZY=@USERID



END
ELSE
BEGIN

CREATE TABLE #SJQXB
(
F_ID VARCHAR(40)
)

DELETE FROM #SJQXB 
EXEC SP_SD_GETUSERSJQX_GS  'YXBMZD_NM',@USERID,'YX_SJQX','YX_SJQXCX','YXSJBMQX','','',@filterSql OUTPUT 
insert into #SJQXB (F_ID)  
exec ('select YXBMZD_NM from YXBMZD where 1=1 '+@filterSql )  


END

	   

INSERT INTO #TEMP(F_GSID,F_BMNM,F_KHNM,F_KHMC,F_CYM1,F_CYM2,F_DQMC,F_SZCS,F_HZSYB,F_QLJBR,F_QYSX,F_JYXZ,F_KHDJ,F_CKDZ,F_KHYB,F_ZCZJ,F_KHYH,F_ZH,F_SH,F_SFBA, F_HKZQ, F_HKFS , F_PSFY,F_KHFY ,F_DBFY,F_ZW,
F_XM,F_XB,F_NL,F_SR,F_DH,F_QQ,F_WX,F_BGDZ,F_AH)
SELECT  YXKHZDGS_GSID F_GSID, YXKHZDGS_BMBH F_BMNM,YXKHZDGS_KHNM F_KHNM,YXKHZDGS_KHMC F_KHMC,YXKHZD_CYMC F_CYM1,YXKHZD_CYMC F_CYM2,YXDQZD_DQMC  F_DQMC,YXDQZD_DQMC  F_SZCS,
YXBMZD_BMMC F_HZSYB,'' F_QLJBR,CASE YXKHZD_QYXZ WHEN '1' THEN '股份制' WHEN '2' THEN '有限责任'  WHEN '9' THEN '其他' END  F_QYSX,YXJYFS_MC F_JYXZ,''F_KHDJ,
YXKHZDGS_ZCDZ F_CKDZ,YXKHZD_YB F_KHYB,YXKHZD_ZCZJ F_ZCZJ,YXYHZD_MC F_KHYH,YXKHZDGS_YHZH F_YHZH,
YXKHZD_SH F_SH,'' F_SFBA,YXKHXY_ZQ F_ZQ,YXKHXY_HKFS F_KHFS,0 F_PSFY,
0 F_KHFY,0 F_DBFY,YXZWZD_MC F_ZW,YXKHRY_XM F_XM,
CASE YXKHRY_XB WHEN '1' THEN '男' WHEN '2' THEN '女' END F_XB,
YXKHRY_NL F_NL, YXKHRY_SR F_SR,YXKHRY_DH F_DH,YXKHRY_QQ F_QQ,YXKHRY_WX F_WX,
'' F_BGDZ,YXKHRY_AH F_AH
FROM YXKHZDGS
 LEFT JOIN YXKHZD ON YXKHZD_NM=YXKHZDGS_KHNM
 LEFT JOIN YXDQZD ON YXDQZD_DQBH=YXKHZD_DQID
 LEFT JOIN YXBMZD ON YXKHZDGS_BMBH=YXBMZD_NM
 LEFT JOIN YXJYFS ON YXJYFS_NM=YXKHZDGS_JYFS
 LEFT JOIN YXYHZD gsda ON gsda.YXYHZD_BH=YXKHZDGS_KHH
 LEFT JOIN YXKHXY ON YXKHZDGS_KHNM=YXKHXY_KHNM
,YXKHRY  LEFT JOIN YXZWZD ON YXZWZD_NM=YXKHRY_ZW
WHERE YXKHZDGS_GID=YXKHRY_LSBH AND 
(YXKHZDGS_GSID=@GSID OR @GSID='') 
AND (YXKHZDGS_KHNM=@KH OR @KH='')
AND (LEFT(YXDQZD_DQBH,2)=@DQ OR @DQ='')










IF @CON>0
BEGIN

SELECT F_KHMC,F_CYM1,F_CYM2,F_DQMC,F_SZCS,F_HZSYB,F_QLJBR,F_QYSX,F_JYXZ,F_KHDJ,F_CKDZ,F_KHYB,F_ZCZJ,F_KHYH,F_ZH,F_SH,F_SFBA, F_HKZQ, F_HKFS , F_PSFY,F_KHFY ,F_DBFY,F_ZW,
F_XM,F_XB,F_NL,F_SR,F_DH,F_QQ,F_WX,F_BGDZ,F_AH 
FROM   #TEMP ,#KHTABLE WHERE F_KHNM=F_KH

END
ELSE
BEGIN

SELECT F_KHMC,F_CYM1,F_CYM2,F_DQMC,F_SZCS,F_HZSYB,F_QLJBR,F_QYSX,F_JYXZ,F_KHDJ,F_CKDZ,F_KHYB,F_ZCZJ,F_KHYH,F_ZH,F_SH,F_SFBA, F_HKZQ, F_HKFS , F_PSFY,F_KHFY ,F_DBFY,F_ZW,
F_XM,F_XB,F_NL,F_SR,F_DH,F_QQ,F_WX,F_BGDZ,F_AH 
FROM   #TEMP ,#SJQXB WHERE F_ID=F_BMNM

END





END

GO

DROP PROC [SP_SDB_ZLFX_90002]
GO


CREATE PROC [SP_SDB_ZLFX_90002]
(
@GSID   VARCHAR(40),--销售公司
@BMNM   VARCHAR(40),--部门
@QDLX   VARCHAR(40),--渠道
@KHNM   VARCHAR(40),--客户名称
@SFQD   VARCHAR(40),--是否显示渠道
@SFKH  VARCHAR(40),--是否显示客户
@USERID varchar(40)
)
AS 
BEGIN
--账龄分析销售部
--销售公司 地区 渠道 客户名称 协议回款期
--品种名称 业务人员 欠款总额 未冲回款金额 不超期金额合计
--超期总计金额 超期15天 超期15-30天 超期30-60天 超期60-90天
--超期90天上 本月欠款 一个月以上-两个月以内欠款 两个月以上-三个月以内欠款 三个月以上-四个月以内欠款
--四个月个月以上-五个月以内欠款 五个月以上-六个月以内欠款 六个月以上欠款
/*
--目前款货余额表中，客户和产品，没有直接的核销关系(有的有)，报表展示的金额列没直接关系，在这报表体现有些尴尬。所以现在这两个字段未处理。
如果处理，需要额外新报表单独处理。
*/

--结果表
CREATE TABLE #TEMP
(
F_GSID VARCHAR(40),
F_QDLX  VARCHAR(40),
F_QYNM  VARCHAR(40),
F_KHNM VARCHAR(40),
F_XYHKQ VARCHAR(40),
F_CPNM VARCHAR(40),
F_RYNM VARCHAR(40),
F_QKZE DECIMAL(20,2),--欠款总额
F_WCHKJE DECIMAL(20,2),--未冲回款金额
F_BCQJEHJ DECIMAL(20,2),--不超期金额合计
F_CQZJE DECIMAL(20,2),--超期金额合计
F_CQ1  DECIMAL(20,2),--超期0-15天
F_CQ2 DECIMAL(20,2),
F_CQ3 DECIMAL(20,2),
F_CQ4 DECIMAL(20,2),
F_CQ5 DECIMAL(20,2),
F_QK1 DECIMAL(20,2),
F_QK2 DECIMAL(20,2),
F_QK3 DECIMAL(20,2),
F_QK4 DECIMAL(20,2),
F_QK5 DECIMAL(20,2),
F_QK6 DECIMAL(20,2),
F_QK7 DECIMAL(20,2)
)

    --将客户编号，公司编号，渠道类型内码，销售区域编号,协议回款期插入到临时表中
	DECLARE  @SQL VARCHAR(3000)
DECLARE @GROUPSQL VARCHAR(1000)
  
    INSERT INTO #TEMP(F_KHNM,F_GSID,F_QDLX,F_QYNM,F_XYHKQ)

	SELECT DISTINCT F_YXKH,F_YXHSDW,YXDDYWLX_NM,BZIRK,YXKHXY_ZQ
	FROM YXHKYEB
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
	LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
	WHERE  (F_YXKH= @KHNM OR @KHNM = '')
	AND (F_YXHSDW = @GSID OR @GSID = '')
	AND (YXDDYWLX_NM = @QDLX OR @QDLX = '')
	AND (F_YXBM=@BMNM OR @BMNM = '') 


	--更新欠款总额
	UPDATE #TEMP
	SET F_QKZE = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH
			)
	--更新未冲回款金额
	UPDATE #TEMP
	SET F_WCHKJE = (SELECT SUM(HK_YE)
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH
			)
	--更新不超期金额合计
	UPDATE #TEMP
	SET F_BCQJEHJ = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND DATEDIFF(DAY,BUDAT,GETDATE()) <= ISNULL(YXKHXY_ZQ,0) AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)




	--更新超期金额合计
	--没有客户协议的，将回款周期更新为0
	UPDATE #TEMP
	SET F_CQZJE = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND DATEDIFF(DAY,BUDAT,GETDATE()) > ISNULL(YXKHXY_ZQ,0) AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)



	--更新超期15天
	UPDATE #TEMP
	SET F_CQ1 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))>0 
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))<=15 
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)




	--更新超期15天-30天
	UPDATE #TEMP
	SET F_CQ2 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))>15 
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))<=30
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

	--更新超期30天-60天
	UPDATE #TEMP
	SET F_CQ3 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))>30 
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))<=60
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

		--更新超期60天-90天
	UPDATE #TEMP
	SET F_CQ4 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))>60 
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))<=90
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

		--更新超期大于90天
	UPDATE #TEMP
	SET F_CQ5 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND (DATEDIFF(DAY,BUDAT,GETDATE()) - ISNULL(YXKHXY_ZQ,0))>90 
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

	--更新本月欠款
	UPDATE #TEMP
	SET F_QK1 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,0,GETDATE()),120)+'01'
			AND CONVERT(VARCHAR(8),DATEADD(MONTH,0,GETDATE()),120)+'31'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)


	--更新一个月以上2个月以内欠款
	UPDATE #TEMP
	SET F_QK2 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-1,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-1,GETDATE()),120)+'31'
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

	--更新2个月以上3个月以内欠款
	UPDATE #TEMP
	SET F_QK3 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-2,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-2,GETDATE()),120)+'31'
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

				--更新3个月以上4个月以内欠款
	UPDATE #TEMP
	SET F_QK4 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-3,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-3,GETDATE()),120)+'31'
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

				--更新4个月以上5个月以内欠款
	UPDATE #TEMP
	SET F_QK5 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-4,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-4,GETDATE()),120)+'31'
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)


				--更新5个月以上6个月以内欠款
	UPDATE #TEMP
	SET F_QK6 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-5,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-5,GETDATE()),120)+'31'
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

	--更新6个月以上欠款
	UPDATE #TEMP
	SET F_QK7 = (
	SELECT  (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND YXXSQY_BH = #TEMP.F_QYNM
			AND BUDAT > CONVERT(VARCHAR(8),DATEADD(MONTH,-6,GETDATE()),120)+'01'
			AND BUDAT NOT LIKE '%0000-00-00%'
		    GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,YXXSQY_BH)

/*
@SFQD   VARCHAR(40),--是否显示渠道
@SFKH  VARCHAR(40),--是否显示客户
@SFRY   VARCHAR(40),--是否显示人员
@SFPZ   VARCHAR(40),--是否显示产品
*/

SET @SQL=' SELECT LSBZDW_DWBH,  LSBZDW_DWMC F_GSID,F_QYNM F_QYNM_NM,YXXSQY_MC F_QYNM, '
SET @GROUPSQL='GROUP BY LSBZDW_DWBH, LSBZDW_DWMC,F_QYNM,YXXSQY_MC '

IF @SFQD='0' --是否显示渠道
BEGIN
SET @SQL=@SQL+'  '''' F_QDLX ,'
END
ELSE
BEGIN
SET @SQL=@SQL+'  YXDDYWLX_MC F_QDLX ,'
SET @GROUPSQL=@GROUPSQL+',YXDDYWLX_MC'
END

IF @SFKH='0' --是否显示客户
BEGIN
SET @SQL=@SQL+'  '''' F_KHMC , '''' F_XYHKQ,'
END
ELSE
BEGIN
SET @SQL=@SQL+'   YXKHZD_KHMC F_KHMC , F_XYHKQ,'
SET @GROUPSQL=@GROUPSQL+' ,YXKHZD_KHMC,F_XYHKQ'
END

SET @SQL=@SQL+'   '''' F_CPMC ,'''' F_RYXM, SUM(F_QKZE)F_QKZE, SUM(F_WCHKJE)F_WCHKJE, SUM(F_BCQJEHJ)F_BCQJEHJ,
 SUM(F_CQZJE)F_CQZJE, SUM(F_CQ1)F_CQ1, SUM(F_CQ2)F_CQ2, SUM(F_CQ3)F_CQ3, SUM(F_CQ4)F_CQ4,
 SUM(F_CQ5)F_CQ5, SUM(F_QK1)F_QK1, SUM(F_QK2)F_QK2, SUM(F_QK3)F_QK3, SUM(F_QK4)F_QK4,
 SUM(F_QK5)F_QK5, SUM(F_QK6)F_QK6, SUM(F_QK7)F_QK7   FROM #TEMP 
  	JOIN YXKHZD ON YXKHZD_NM=F_KHNM
	JOIN LSBZDW ON LSBZDW_DWBH = F_GSID
	LEFT JOIN YXDDYWLX ON YXDDYWLX_NM = F_QDLX
	LEFT JOIN YXXSQY ON YXXSQY_BH = F_QYNM '+@GROUPSQL
print (@SQL)
EXEC (@SQL)




END




GO








GO






DROP PROC [SP_SDB_ZLFX_90005]
GO

CREATE PROC [SP_SDB_ZLFX_90005]
(
@NY VARCHAR(40),
@GSID VARCHAR(40),
@QDLX   VARCHAR(40),
@BMNM   VARCHAR(40),
@KHNM   VARCHAR(40),
@USERID varchar(40)
)
AS 
BEGIN
--账龄分析商务部
--事业部 大区 省区 核算单位 客户名称
--回款周期 法定委托人 实际负责人 实时欠款 未核销回款
--年度发货合计 年度回款合计 年度回款发货比 本(N)月发货 上(N-1)月发货
--上(N-1)月实际回款 上(N-1)月回款计划 上(N-1)月回款计划完成率 本（N）月应收 上(N-1)月应收
--(N-2)月应收 (N-3)月应收 (N-4)月应收 (N-5)月应收 (N-6)月及以上应收 本（N）月回款计划

CREATE TABLE #TEMP
(
F_GSID VARCHAR(40),--核算单位U
F_QDLX  VARCHAR(40),--渠道U
F_BMNM VARCHAR(40),--办事处（省区）U
F_KHNM VARCHAR(40),--客户U
F_HKZQ VARCHAR(40),--回款周期U
F_FDWTR VARCHAR(40),--法定委托人
F_SJFZR VARCHAR(40),--实际负责人U
F_SSQK DECIMAL(20,2),--实时欠款
F_WHXHK DECIMAL(20,2),--未核销欠款
F_NDFHHJ DECIMAL(20,2),--发货合计U
F_NDHKHJ DECIMAL(20,2),--回款合计U
F_NDHKFHB  DECIMAL(20,2),--回款发货比 
F_BYFH DECIMAL(20,2),--本月发货
F_SYFH DECIMAL(20,2),--上月发货
F_SYSJHK DECIMAL(20,2),--上月回款
F_SYHKJH DECIMAL(20,2),--上月回款计划
F_SYHKFHWCL DECIMAL(20,2),--上月回款计划完成率
F_YYS0 DECIMAL(20,2),--本月应收
F_YYS1 DECIMAL(20,2),--本月应收
F_YYS2 DECIMAL(20,2),--本月应收
F_YYS3 DECIMAL(20,2),--本月应收
F_YYS4 DECIMAL(20,2),--本月应收
F_YYS5 DECIMAL(20,2),--本月应收
F_YYS6 DECIMAL(20,2),--本月应收
F_BYHKJH DECIMAL(20,2)--本月回款计划
)


 INSERT INTO #TEMP(F_GSID,F_QDLX,F_BMNM,F_KHNM,F_HKZQ,F_NDFHHJ,F_NDHKHJ)
	SELECT F_GSID,F_QDLX,F_BMNM,F_KHNM,F_HKZQ,SUM(F_FHJE)F_FHJE,SUM(F_HKJE)F_HKJE FROM (
    SELECT  YXERPFH_GSID F_GSID,YXDDYWLX_NM F_QDLX,YXERPFH_YXBSC F_BMNM,YXERPFH_KH F_KHNM,ISNULL(YXKHXY_ZQ,'') F_HKZQ,ISNULL(YXERPFH_JE,0) F_FHJE,0 F_HKJE FROM       YXERPFH LEFT JOIN YXKHXY ON YXKHXY_KHNM = YXERPFH_KH
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH=YXERPFH_C9
	WHERE YXERPFH_ND=LEFT(@NY,4)
    AND (YXERPFH_GSID=@GSID OR @GSID='') 
	AND (YXDDYWLX_NM=@QDLX OR @QDLX='')
	AND (YXERPFH_YXBSC=@BMNM OR @BMNM='')
	AND (YXERPFH_KH=@KHNM OR @KHNM='')
	 UNION ALL
	 SELECT ISNULL(YXRKD_GSID,''),ISNULL(YXRKD_QDLX,''),ISNULL(YXRKD_BMBH,''),ISNULL(YXRKD_KH,''),ISNULL(YXKHXY_ZQ,0) F_HKZQ,0 F_FHJE,ISNULL(YXRKD_JE,0) F_HKJE
	 FROM YXRKD  LEFT JOIN YXKHXY ON YXKHXY_KHNM = YXRKD_KH
	 WHERE YXRKD_ND=LEFT(@NY,4)
     AND (YXRKD_GSID=@GSID OR @GSID='') 
	 AND (YXRKD_QDLX=@QDLX OR @QDLX='')
	 AND (YXRKD_BMBH=@BMNM OR @BMNM='')
	 AND (YXRKD_KH=@KHNM OR @KHNM='')
	 UNION ALL
	SELECT DISTINCT F_YXHSDW,YXDDYWLX_NM,F_YXBM,F_YXKH,ISNULL(YXKHXY_ZQ,0) YXKHXY_ZQ,0 F_FHJE,0 F_HKJE
	FROM YXHKYEB
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
	LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
	LEFT JOIN YXKHXY ON YXKHXY_KHNM = F_YXKH  
	WHERE (F_YXKH= @KHNM OR @KHNM = '')
	AND (F_YXHSDW = @GSID OR @GSID = '')
	AND (YXDDYWLX_NM = @QDLX OR @QDLX = '')
	AND (F_YXBM=@BMNM OR @BMNM = '') 
	 )LSB GROUP BY F_GSID,F_QDLX,F_BMNM,F_KHNM,F_HKZQ

	 --更新实际负责人
	 UPDATE #TEMP SET F_SJFZR=YXCZYKH_YWY FROM 
	 (	 SELECT YXCZYKH_YWY,YXCZYKHMX_KH FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH)LSB
	 WHERE F_KHNM=YXCZYKHMX_KH



	--更新实时欠款
	UPDATE #TEMP
	SET F_SSQK = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND F_YXBM = #TEMP.F_BMNM
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)
   
	--更新未核销欠款,款货余额未核销提单F_WHXHK
	UPDATE #TEMP
	SET F_WHXHK = (
	SELECT  SUM(SD_YE)
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND F_YXBM = #TEMP.F_BMNM
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)

    --更新年度回款发货比
	UPDATE #TEMP SET  F_NDHKFHB= CASE WHEN  F_NDFHHJ=0 THEN 0 ELSE   F_NDHKHJ*100/F_NDFHHJ END

	--更新本月发货
	UPDATE #TEMP SET F_BYFH=F_FHJE FROM  ( SELECT  YXERPFH_GSID F_GSID,YXDDYWLX_NM F_QDLX,YXERPFH_YXBSC F_BMNM,YXERPFH_KH F_KHNM,SUM(ISNULL(YXERPFH_JE,0)) F_FHJE FROM       YXERPFH 
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH=YXERPFH_C9
	WHERE YXERPFH_NY=@NY
    AND (YXERPFH_GSID=@GSID OR @GSID='') 
	AND (YXDDYWLX_NM=@QDLX OR @QDLX='')
	AND (YXERPFH_YXBSC=@BMNM OR @BMNM='')
	AND (YXERPFH_KH=@KHNM OR @KHNM='')
	GROUP BY YXERPFH_GSID,YXDDYWLX_NM,YXERPFH_YXBSC,YXERPFH_KH
	 )LSB
	WHERE LSB.F_GSID=#TEMP.F_GSID
	AND LSB.F_QDLX=#TEMP.F_QDLX
	AND LSB.F_BMNM=#TEMP.F_BMNM
	AND LSB.F_KHNM=#TEMP.F_KHNM		   


	--更新上月发货
		UPDATE #TEMP SET F_SYFH=F_FHJE FROM ( SELECT  YXERPFH_GSID F_GSID,YXDDYWLX_NM F_QDLX,YXERPFH_YXBSC F_BMNM,YXERPFH_KH F_KHNM,SUM(ISNULL(YXERPFH_JE,0)) F_FHJE FROM       YXERPFH 
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH=YXERPFH_C9
	WHERE YXERPFH_NY=CONVERT(VARCHAR(6),DATEADD(MONTH,-1,@NY+'01'),112)
    AND (YXERPFH_GSID=@GSID OR @GSID='') 
	AND (YXDDYWLX_NM=@QDLX OR @QDLX='')
	AND (YXERPFH_YXBSC=@BMNM OR @BMNM='')
	AND (YXERPFH_KH=@KHNM OR @KHNM='')
		GROUP BY YXERPFH_GSID,YXDDYWLX_NM,YXERPFH_YXBSC,YXERPFH_KH
	 )LSB
	WHERE LSB.F_GSID=#TEMP.F_GSID
	AND LSB.F_QDLX=#TEMP.F_QDLX
	AND LSB.F_BMNM=#TEMP.F_BMNM
	AND LSB.F_KHNM=#TEMP.F_KHNM	

	--更新上月实际回款
			UPDATE #TEMP SET F_SYSJHK=F_HKJE FROM ( 	 SELECT ISNULL(YXRKD_GSID,'') F_GSID,ISNULL(YXRKD_QDLX,'') F_QDLX,ISNULL(YXRKD_BMBH,'') F_BMNM,ISNULL(YXRKD_KH,'') F_KHNM,SUM(ISNULL(YXRKD_JE,0)) F_HKJE
	 FROM YXRKD 
	 WHERE  YXRKD_NY=CONVERT(VARCHAR(6),DATEADD(MONTH,-1,@NY+'01'),112)
     AND (YXRKD_GSID=@GSID OR @GSID='') 
	 AND (YXRKD_QDLX=@QDLX OR @QDLX='')
	 AND (YXRKD_BMBH=@BMNM OR @BMNM='')
	 AND (YXRKD_KH=@KHNM OR @KHNM='')
	 GROUP BY  ISNULL(YXRKD_GSID,'') ,ISNULL(YXRKD_QDLX,'') ,ISNULL(YXRKD_BMBH,'') ,ISNULL(YXRKD_KH,'') 
	  )LSB
	WHERE LSB.F_GSID=#TEMP.F_GSID
	AND LSB.F_QDLX=#TEMP.F_QDLX
	AND LSB.F_BMNM=#TEMP.F_BMNM
	AND LSB.F_KHNM=#TEMP.F_KHNM	

	--上月回款计划
	
	UPDATE #TEMP SET F_SYHKJH=YXYJHKMX_JHTZ FROM (
	SELECT  DISTINCT YXYJHK_GSID,  YXDDYWLX_NM,  YXYJHK_BMBH,YXYJHKMX_KH,YXYJHKMX_JHTZ FROM YXYJHKMX, YXYJHK 	LEFT JOIN YXDDYWLX ON YXDDYWLX_SYB=YXYJHK_SYB WHERE YXYJHK_LSBH=YXYJHKMX_LSBH AND YXYJHK_YEAR=CONVERT(VARCHAR(6),DATEADD(MONTH,-1,@NY+'01'),112)
	)LSB  WHERE F_KHNM=YXYJHKMX_KH AND F_GSID=YXYJHK_GSID AND YXDDYWLX_NM=F_QDLX AND YXYJHK_BMBH=F_BMNM

	--本月回款计划
	UPDATE #TEMP SET F_BYHKJH=YXYJHKMX_JHTZ FROM (
	SELECT  DISTINCT YXYJHK_GSID,  YXDDYWLX_NM,  YXYJHK_BMBH,YXYJHKMX_KH,YXYJHKMX_JHTZ FROM YXYJHKMX, YXYJHK 	LEFT JOIN YXDDYWLX ON YXDDYWLX_SYB=YXYJHK_SYB WHERE YXYJHK_LSBH=YXYJHKMX_LSBH AND YXYJHK_YEAR=@NY
	)LSB  WHERE F_KHNM=YXYJHKMX_KH AND F_GSID=YXYJHK_GSID AND YXDDYWLX_NM=F_QDLX AND YXYJHK_BMBH=F_BMNM

	--上月回款计划完成率
	UPDATE #TEMP SET F_SYHKFHWCL=CASE WHEN ISNULL(F_SYHKJH,0)=0 THEN 0 ELSE  F_SYSJHK*100/F_SYHKJH END

	--更新本(N)月应收
	UPDATE #TEMP
	SET F_YYS0 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
	        AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,0,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,0,GETDATE()),120)+'31'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)





	--更新(N-1)月应收
	UPDATE #TEMP
	SET F_YYS1 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-1,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-1,GETDATE()),120)+'31'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)


	--更新(N-2)月应收
	UPDATE #TEMP
	SET F_YYS2 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-2,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-2,GETDATE()),120)+'31'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)

	
	--更新(N-3)月应收
	UPDATE #TEMP
	SET F_YYS3 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-3,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-3,GETDATE()),120)+'31'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)

	
	--更新(N-4)月应收
	UPDATE #TEMP
	SET F_YYS4 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-4,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-4,GETDATE()),120)+'31'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)

	
	--更新(N-5)月应收
	UPDATE #TEMP
	SET F_YYS5 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT BETWEEN CONVERT(VARCHAR(8),DATEADD(MONTH,-5,GETDATE()),120)+'01'
						AND CONVERT(VARCHAR(8),DATEADD(MONTH,-5,GETDATE()),120)+'31'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)


	--更新(N-6)及以上月应收
	UPDATE #TEMP
	SET F_YYS6 = (SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXXSQY ON YXXSQY_BH = BZIRK
			WHERE F_YXKH = #TEMP.F_KHNM
			AND F_YXHSDW = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND F_YXBM = #TEMP.F_BMNM
			AND BUDAT <= CONVERT(VARCHAR(8),DATEADD(MONTH,-6,GETDATE()),120)+'01'
			GROUP BY F_YXKH,F_YXHSDW,YXDDYWLX_NM,F_YXBM)


			SELECT LSBZDW_DWBH, LSBZDW_DWMC  F_GSID,YXDDYWLX_NM,YXDDYWLX_MC F_QDLX  ,YXBMZD_NM,YXBMZD_BMMC F_BMNM,YXKHZD_NM,YXKHZD_KHMC F_KHNM ,F_HKZQ, F_FDWTR,F_SJFZR,F_SSQK, F_WHXHK,F_NDHKHJ,F_NDFHHJ, F_NDHKFHB, F_BYFH, F_SYFH, F_SYSJHK, F_SYHKJH, F_SYHKFHWCL, F_YYS0,F_YYS1 ,F_YYS2, F_YYS3, F_YYS4, F_YYS5, F_YYS6, F_BYHKJH  FROM #TEMP
			  LEFT JOIN LSBZDW ON LSBZDW_DWBH=F_GSID
			  LEFT JOIN YXDDYWLX ON YXDDYWLX_NM=F_QDLX
              LEFT JOIN YXBMZD ON YXBMZD_NM=F_BMNM
              LEFT JOIN YXKHZD ON YXKHZD_NM=F_KHNM



END
GO



DROP  PROC [SP_SDB_FHHKQSFX_90006_NEW]
GO
CREATE PROC [SP_SDB_FHHKQSFX_90006_NEW]
(
@KSNY  VARCHAR(40),--开始年月
@JSNY  VARCHAR(40),--结束年月
@GSID   VARCHAR(40),--销售公司
@QDLX  VARCHAR(40),-- 前台传递渠道类型
@BMNM   VARCHAR(40),--省区（部门）
@KHNM   VARCHAR(40),--客户
@SFGSID   VARCHAR(40),--是否显示GSID
@SFQDLX   VARCHAR(40),--是否事业部
@SFBMNM   VARCHAR(40),--是否显示办事处
@SFKH   VARCHAR(40),--是否显示客户
@USERID varchar(40)
)
AS 
BEGIN
--EXEC SP_SDB_FHHKQSFX_90006_NEW '201901','201903','','','','ea1d08d3-9295-46f1-9375-438983102d18','0','0','0','1','0000'
--exec SP_SDB_FHHKQSFX_90006_NEW @KSNY=N'201901',@JSNY=N'201911',@GSID=N'',@SYB=N'',@DQ=N'',@SQ=N'',@KHNM=N'',@SFGSID=N'1',@SFSYB=N'0',@SFDQ=N'0',@SFSQ=N'0',@SFKH=N'0',@USERID=N'chenhl'
--发货回款趋势分析

DECLARE  @SQL VARCHAR(3000)
DECLARE @GROUPSQL VARCHAR(1000)
DECLARE @CON INT

SET @SQL=' '
SET @GROUPSQL=' '

--中间表
CREATE TABLE #TEMP
(
F_GSID VARCHAR(40),--核算单位
F_QDLX  VARCHAR(40),--渠道
F_BMNM VARCHAR(40),--办事处（省区）
F_KHNM VARCHAR(40),--客户
F_HKZQ VARCHAR(40),--回款周期
F_FDWTR VARCHAR(40),--法定委托人
F_SJFZR VARCHAR(40),--实际负责人
F_SSQK DECIMAL(20,2),--实时欠款
F_FHHJ DECIMAL(20,2),--发货合计（先明细,再动态group by ）
F_HKHJ DECIMAL(20,2),--回款合计（先明细,再动态group by ）
F_HKFHB  DECIMAL(20,2),--回款发货比 （动态group by 后再计算）
F_YJHK DECIMAL(20,2),--月均回款 （动态group by 后再计算）
F_PJHKZQ DECIMAL(20,2),--平均回款周期 （动态group by 后再计算）
F_NY VARCHAR(40),--年月(转置列)
F_HKJE DECIMAL(20,2),--回款金额
F_FHJE DECIMAL(20,2)--发货金额
)

--结果表
CREATE TABLE #TEMPRETURN
(
F_GSID VARCHAR(40),--核算单位
F_QDLX  VARCHAR(40),--渠道
F_BMNM VARCHAR(40),--办事处（省区）
F_KHNM VARCHAR(40),--客户
F_HKZQ VARCHAR(40),--回款周期
F_FDWTR VARCHAR(40),--法定委托人
F_SJFZR VARCHAR(40),--实际负责人
F_SSQK DECIMAL(20,2),--实时欠款
F_FHHJ DECIMAL(20,2),--发货合计（先明细,再动态group by ）
F_HKHJ DECIMAL(20,2),--回款合计（先明细,再动态group by ）
F_HKFHB  DECIMAL(20,2),--回款发货比 （动态group by 后再计算）
F_YJHK DECIMAL(20,2),--月均回款 （动态group by 后再计算）
F_PJHKZQ DECIMAL(20,2),--平均回款周期 （动态group by 后再计算）
F_NY VARCHAR(40),--年月(转置列)
F_HKJE DECIMAL(20,2),--回款金额
F_FHJE DECIMAL(20,2)--发货金额
)

CREATE TABLE #NY
(
F_NY VARCHAR(6)
)
--找出两个日期之间相差的月份数.然后从最小累加1月至最大的月份.
declare @start  datetime   
declare @end    datetime   
--set @start = '20181201'   
--set @end = '20190801' 
set @start = @KSNY +'01'  
set @end = @JSNY   +'01'
  
INSERT INTO #NY(F_NY)
select convert(nvarchar(6),dateadd(m,a.number,convert(datetime,convert(nvarchar(7),@start,120)+'-01')),112) month_you_need   
FROM (select number from master.dbo.spt_values where type='p') a
where a.number<=datediff(m,dateadd(m,a.number,convert(datetime,convert(nvarchar(7),@start,120)+'-01')),dateadd(m,a.number,convert(datetime,convert(nvarchar(7),@end,120)+'-01')))
--获取月份的个数
SELECT @CON=COUNT(*) FROM #NY






	     --
    INSERT INTO #TEMP(F_GSID,F_QDLX,F_BMNM,F_KHNM,F_HKZQ,F_NY,F_FHJE,F_HKJE)

	SELECT F_GSID,F_QDLX,F_BMNM,F_KHNM,F_ZQ,F_NY,SUM(F_FHJE)F_FHJE,SUM(F_HKJE)F_HKJE FROM (
    SELECT  YXERPFH_GSID F_GSID,YXDDYWLX_NM F_QDLX,YXERPFH_YXBSC F_BMNM,YXERPFH_KH F_KHNM,ISNULL(YXKHXY_ZQ,'') F_ZQ,LEFT(YXERPFH_YWRQ,6)F_NY,ISNULL(YXERPFH_JE,0) F_FHJE,0 F_HKJE FROM       YXERPFH LEFT JOIN YXKHXY ON YXKHXY_KHNM = YXERPFH_KH
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH=YXERPFH_C9
	WHERE LEFT(YXERPFH_YWRQ,6) BETWEEN @KSNY AND @JSNY
    AND (YXERPFH_GSID=@GSID OR @GSID='') 
	AND (YXDDYWLX_NM=@QDLX OR @QDLX='')
	AND (YXERPFH_YXBSC=@BMNM OR @BMNM='')
	AND (YXERPFH_KH=@KHNM OR @KHNM='')
	 UNION ALL
	 SELECT ISNULL(YXRKD_GSID,''),ISNULL(YXRKD_QDLX,''),ISNULL(YXRKD_BMBH,''),ISNULL(YXRKD_KH,''),ISNULL(YXKHXY_ZQ,0) YXKHXY_ZQ,LEFT(YXRKD_SKRQ,6) F_NY,0 F_FHJE,ISNULL(YXRKD_JE,0) F_HKJE
	 FROM YXRKD  LEFT JOIN YXKHXY ON YXKHXY_KHNM = YXRKD_KH
	 WHERE  LEFT(YXRKD_SKRQ,6) BETWEEN @KSNY AND @JSNY
     AND (YXRKD_GSID=@GSID OR @GSID='') 
	 AND (YXRKD_QDLX=@QDLX OR @QDLX='')
	 AND (YXRKD_BMBH=@BMNM OR @BMNM='')
	 AND (YXRKD_KH=@KHNM OR @KHNM='')
	 )LSB GROUP BY F_GSID,F_QDLX,F_BMNM,F_KHNM,F_ZQ,F_NY

	 --更新实际负责人
	 UPDATE #TEMP SET F_SJFZR=YXCZYKH_YWY FROM 
	 (	 SELECT YXCZYKH_YWY,YXCZYKHMX_KH FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH )LSB
	 WHERE F_KHNM=YXCZYKHMX_KH


	 --更新发货合计和回款合计
	 UPDATE #TEMP SET F_FHHJ=LSB.F_FHJE,F_HKHJ=LSB.F_HKJE FROM (
	 SELECT F_GSID,F_QDLX,F_BMNM,F_KHNM,SUM(F_FHJE)F_FHJE,SUM(F_HKJE)F_HKJE 
	 FROM #TEMP
	 WHERE F_NY BETWEEN @KSNY AND @JSNY
	 GROUP BY F_GSID,F_QDLX,F_BMNM,F_KHNM
	 ) LSB
	  WHERE 
	  LSB.F_GSID=#TEMP.F_GSID
	  AND LSB.F_QDLX=#TEMP.F_QDLX
	  AND LSB.F_BMNM=#TEMP.F_BMNM
	  AND LSB.F_KHNM=#TEMP.F_KHNM



	 --更新实时欠款
	UPDATE #TEMP
	SET F_SSQK = (			
	        SELECT (SUM(SD_YE)-SUM(HK_YE))
			FROM YXHKYEB
			LEFT JOIN YXSJYS DW ON DWBH = DW.YXSJYS_WWBH
	        JOIN LSBZDW ON LSBZDW_DWBH = DW.YXSJYS_YXBH
			LEFT JOIN YXDDYWLX ON YXDDYWLX_BH = VTWEG
			LEFT JOIN YXSJYS BM ON BM.YXSJYS_WWBH=BZIRK AND BM.YXSJYS_C1=YXDDYWLX_BH AND BM.YXSJYS_YSFL ='04'  AND BM.YXSJYS_WWXT='04' 
			LEFT JOIN  YXKHZD ON YXKHZD_KHBH = SUBSTRING(KUNNR,2,LEN(KUNNR)-1)
			WHERE YXKHZD_NM = #TEMP.F_KHNM
			AND LSBZDW_DWBH = #TEMP.F_GSID
	        AND YXDDYWLX_NM = #TEMP.F_QDLX
			AND BM.YXSJYS_YXBH=#TEMP.F_BMNM
			GROUP BY YXKHZD_NM, LSBZDW_DWBH,YXDDYWLX_NM,BM.YXSJYS_YXBH
			)


   --根据是否显示的维度取汇总数据
SET @SQL=@SQL+' INSERT INTO #TEMPRETURN(F_NY,F_GSID ,F_QDLX ,F_BMNM ,F_KHNM ,F_HKZQ,F_FDWTR,F_SJFZR,F_FHJE,F_HKJE,F_FHHJ,F_HKHJ  )
   SELECT  F_NY,'

SET @GROUPSQL=@GROUPSQL+' GROUP BY F_NY '


IF @SFGSID='0' --是否显示GSID
BEGIN
SET @SQL=@SQL+'  '''' F_GSID ,'

END
ELSE
BEGIN
SET @SQL=@SQL+'  F_GSID, '
SET @GROUPSQL=@GROUPSQL+',F_GSID '

END


IF @SFQDLX='0' --是否事业部
BEGIN
SET @SQL=@SQL+'  ''''  F_QDLX, '

END
ELSE
BEGIN
SET @SQL=@SQL+' F_QDLX , '
SET @GROUPSQL=@GROUPSQL+' ,F_QDLX'

END


IF @SFBMNM='0' --是否显示部门
BEGIN
SET @SQL=@SQL+'  '''' F_BMNM,'

END
ELSE
BEGIN
SET @SQL=@SQL+' F_BMNM, '
SET @GROUPSQL=@GROUPSQL+ ' ,F_BMNM'

END


IF @SFKH='0' --是否显示客户
BEGIN
SET @SQL=@SQL+'  '''' F_KHNM,''''F_HKZQ,'''' F_FDWTR,'''' F_SJFZR,  '

END
ELSE
BEGIN
SET @SQL=@SQL+' F_KHNM,F_HKZQ,F_FDWTR,F_SJFZR, '
SET @GROUPSQL=@GROUPSQL+',F_KHNM,F_HKZQ,F_FDWTR,F_SJFZR'

END

SET @SQL=@SQL+'  SUM(F_FHJE) F_FHJE, SUM(F_HKJE) F_HKJE,SUM(F_FHHJ) F_FHHJ, SUM(F_HKHJ) F_HKHJ FROM #TEMP  '

--拼接完整的SQL语句
SET @SQL=@SQL+@GROUPSQL
PRINT(@SQL)
EXEC(@SQL)



	 --更新发货合计和回款合计
	 UPDATE #TEMPRETURN SET F_FHHJ=LSB.F_FHJE,F_HKHJ=LSB.F_HKJE FROM (
	 SELECT F_GSID,F_QDLX,F_BMNM,F_KHNM,SUM(F_FHJE)F_FHJE,SUM(F_HKJE)F_HKJE 
	 FROM #TEMPRETURN
	 WHERE F_NY BETWEEN @KSNY AND @JSNY
	 GROUP BY F_GSID,F_QDLX,F_BMNM,F_KHNM
	 ) LSB
	  WHERE 
	  LSB.F_GSID=#TEMPRETURN.F_GSID
	  AND LSB.F_QDLX=#TEMPRETURN.F_QDLX
	  AND LSB.F_BMNM=#TEMPRETURN.F_BMNM
	  AND LSB.F_KHNM=#TEMPRETURN.F_KHNM






--更新年度回款发货比、更新月均回款、更新平均回款周期
			UPDATE #TEMPRETURN SET F_HKFHB = CASE WHEN F_FHHJ=0 THEN 0 ELSE ROUND(F_HKHJ*100/F_FHHJ,2) END ,F_YJHK=F_HKHJ/@CON,F_PJHKZQ=CASE WHEN F_HKHJ=0 THEN 0 ELSE ROUND(F_FHHJ*100/F_HKHJ,2) END 


  SELECT LSBZDW_DWBH, LSBZDW_DWMC  F_GSID,YXDDYWLX_NM,YXDDYWLX_MC F_QDLX  ,YXBMZD_NM,YXBMZD_BMMC F_BMNM,YXKHZD_NM,YXKHZD_KHMC F_KHNM ,F_HKZQ,F_FDWTR ,F_SJFZR ,F_SSQK ,F_FHHJ,F_HKHJ,F_HKFHB ,F_YJHK,F_PJHKZQ,F_NY ,F_HKJE,F_FHJE  FROM #TEMPRETURN 
  LEFT JOIN LSBZDW ON LSBZDW_DWBH=F_GSID
  LEFT JOIN YXDDYWLX ON YXDDYWLX_NM=F_QDLX
  LEFT JOIN YXBMZD ON YXBMZD_NM=F_BMNM
  LEFT JOIN YXKHZD ON YXKHZD_NM=F_KHNM
  ORDER BY LSBZDW_DWMC, YXDDYWLX_MC,YXBMZD_BMMC,YXKHZD_KHMC,F_HKZQ,F_FDWTR,F_SJFZR,F_SSQK,F_FHHJ,F_HKHJ,F_HKFHB,F_YJHK,F_PJHKZQ,F_NY





END

GO


DROP PROC [SP_SDB_PJHKZQ_90007]
GO
CREATE PROC [SP_SDB_PJHKZQ_90007]
(
@KSRQ VARCHAR(40),
@JSRQ VARCHAR(40),
@KHNM   VARCHAR(40),
@GSID VARCHAR(40),
@QDLX   VARCHAR(40),
@BMNM   VARCHAR(40),
@USERID varchar(40)
)
AS 
BEGIN
--平均回款周期分析
--EXEC SP_SDB_PJHKZQ_90007 '20190101','20190201','','','','','',''
--SELECT '1' F_KHMC,'2' F_HSDW,'3' F_JBR,'' F_SYB,'' F_DQ,'' F_BM,'' F_KSRQ,'' F_JSRQ,'' F_RJQK,'' F_RJHK,'' F_SJHKZQ

CREATE TABLE #TEMP
(
F_KHNM VARCHAR(40),
F_GSID VARCHAR(40),
F_JBR VARCHAR(40),
F_QDLX VARCHAR(40),
F_BMNM VARCHAR(40),
F_KSRQ VARCHAR(40),
F_JSRQ VARCHAR(40),
F_TS INT,
F_FHJE DECIMAL(20,2),
F_HKJE DECIMAL(20,2),
F_RJQK DECIMAL(20,2),
F_RJHK DECIMAL(20,2),
F_SJHKZQ DECIMAL(20,2)
)





--新建客户表
    DECLARE @filterSql varchar(4000) ---过滤串
	DECLARE @CON INT
CREATE TABLE #KHTABLE
(
F_KH VARCHAR(40)
)
SELECT @CON=COUNT(*) FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH AND YXCZYKH_CZY=@USERID
--操作员和客户关系表有数据
IF @CON>0
BEGIN

INSERT INTO #KHTABLE(F_KH)
SELECT YXCZYKHMX_KH FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH AND YXCZYKH_CZY=@USERID

END
ELSE
BEGIN

CREATE TABLE #SJQXB
(
F_ID VARCHAR(40)
)

DELETE FROM #SJQXB 
EXEC SP_SD_GETUSERSJQX_GS  'YXBMZD_NM',@USERID,'YX_SJQX','YX_SJQXCX','YXSJBMQX','','',@filterSql OUTPUT 
insert into #SJQXB (F_ID)  
exec ('select YXBMZD_NM from YXBMZD where 1=1 '+@filterSql )  
END



    --根据发货把需要的基础列插入临时表(选择YXERPFH的)
    INSERT INTO #TEMP(F_GSID,F_QDLX,F_BMNM,F_KHNM,F_KSRQ,F_JSRQ,F_TS,F_FHJE,F_HKJE)
	SELECT F_GSID,F_QDLX,F_BMNM,F_KHNM,@KSRQ,@JSRQ,DATEDIFF(DAY,@KSRQ,@JSRQ) F_TS,SUM(F_FHJE)F_FHJE,SUM(F_HKJE)F_HKJE FROM (
    SELECT  YXERPFH_GSID F_GSID,YXDDYWLX_NM F_QDLX,YXERPFH_YXBSC F_BMNM,YXERPFH_KH F_KHNM,ISNULL(YXKHXY_ZQ,'') F_ZQ,LEFT(YXERPFH_YWRQ,6)F_NY,ISNULL(YXERPFH_JE,0) F_FHJE,0 F_HKJE FROM       YXERPFH LEFT JOIN YXKHXY ON YXKHXY_KHNM = YXERPFH_KH
	LEFT JOIN YXDDYWLX ON YXDDYWLX_BH=YXERPFH_C9
	WHERE YXERPFH_YWRQ BETWEEN @KSRQ AND @JSRQ
    AND (YXERPFH_GSID=@GSID OR @GSID='') 
	AND (YXDDYWLX_NM=@QDLX OR @QDLX='')
	AND (YXERPFH_YXBSC=@BMNM OR @BMNM='')
	AND (YXERPFH_KH=@KHNM OR @KHNM='')
	 UNION ALL
	 SELECT ISNULL(YXRKD_GSID,''),ISNULL(YXRKD_QDLX,''),ISNULL(YXRKD_BMBH,''),ISNULL(YXRKD_KH,''),ISNULL(YXKHXY_ZQ,0) YXKHXY_ZQ,LEFT(YXRKD_SKRQ,6) F_NY,0 F_FHJE,ISNULL(YXRKD_JE,0) F_HKJE
	 FROM YXRKD  LEFT JOIN YXKHXY ON YXKHXY_KHNM = YXRKD_KH
	 WHERE  YXRKD_SKRQ BETWEEN @KSRQ AND @JSRQ
     AND (YXRKD_GSID=@GSID OR @GSID='') 
	 AND (YXRKD_QDLX=@QDLX OR @QDLX='')
	 AND (YXRKD_BMBH=@BMNM OR @BMNM='')
	 AND (YXRKD_KH=@KHNM OR @KHNM='')
	 )LSB GROUP BY F_GSID,F_QDLX,F_BMNM,F_KHNM



	 --

		 --更新经办人
	 UPDATE #TEMP SET F_JBR=YXCZYKH_YWY FROM 
	 (	 SELECT YXCZYKH_YWY,YXCZYKHMX_KH FROM YXCZYKH,YXCZYKHMX WHERE YXCZYKH_LSBH=YXCZYKHMX_FLBH )LSB
	 WHERE F_KHNM=YXCZYKHMX_KH

	 --更新日均欠款(取该期间内的提单金额YXERPFH/期间天数)\更新日均回款(期间内回款合计认款单/期间天数)
	 UPDATE #TEMP SET F_RJQK= CASE WHEN  F_TS=0 THEN 0 ELSE F_FHJE/F_TS END, F_RJHK=CASE WHEN  F_TS=0 THEN 0 ELSE F_HKJE/F_TS END
   	 --更新日均回款(日均欠款/日均回款)
	 UPDATE #TEMP SET F_SJHKZQ=CASE WHEN F_RJQK=0 THEN 0 ELSE F_RJQK*100/F_RJHK END


	 

IF @CON>0
--取业务员客户关联表
BEGIN

	 SELECT  YXKHZD_KHMC F_KH,LSBZDW_DWMC F_GSID,YXRYZD_RYXM F_JBR ,YXDDYWLX_MC F_QDLX ,YXBMZD_BMMC F_BMNM ,F_KSRQ ,F_JSRQ ,F_TS ,F_RJQK ,F_RJHK ,F_SJHKZQ  FROM #TEMP
	 LEFT JOIN YXKHZD ON YXKHZD_NM=F_KHNM
	 LEFT JOIN LSBZDW ON LSBZDW_DWBH=F_GSID
	 LEFT JOIN YXRYZD ON YXRYZD_NM=F_JBR
	 LEFT JOIN YXDDYWLX ON YXDDYWLX_NM=F_QDLX
	 LEFT JOIN YXBMZD ON YXBMZD_NM=F_BMNM
     ,#KHTABLE WHERE F_KHNM=F_KH

END
ELSE
BEGIN
	 SELECT  YXKHZD_KHMC F_KH,LSBZDW_DWMC F_GSID,YXRYZD_RYXM F_JBR ,YXDDYWLX_MC F_QDLX ,YXBMZD_BMMC F_BMNM ,F_KSRQ ,F_JSRQ ,F_TS ,F_RJQK ,F_RJHK ,F_SJHKZQ  FROM #TEMP
	 LEFT JOIN YXKHZD ON YXKHZD_NM=F_KHNM
	 LEFT JOIN LSBZDW ON LSBZDW_DWBH=F_GSID
	 LEFT JOIN YXRYZD ON YXRYZD_NM=F_JBR
	 LEFT JOIN YXDDYWLX ON YXDDYWLX_NM=F_QDLX
	 LEFT JOIN YXBMZD ON YXBMZD_NM=F_BMNM
	 ,#SJQXB WHERE F_ID=YXBMZD_NM

END
END
GO


DROP PROC SP_SDB_QDCBFX_90008
GO
CREATE PROC SP_SDB_QDCBFX_90008
(
@KSRQ VARCHAR(40),
@JSRQ VARCHAR(40),
@KH   VARCHAR(40),
@GSID VARCHAR(40),
@SYB   VARCHAR(40),
@DQ   VARCHAR(40),
@BMBH   VARCHAR(40),
@USERID varchar(40)
)
AS 
BEGIN
--渠道成本分析



SELECT '11' F_SYB,'' F_DQ,'' F_BSC,'' F_GSID,'' F_KH,
'' F_FDWTR,'' F_SJWTR,'' F_NDJE,'' F_NDGWJE,'' F_NDCB,
'' F_YDJE1,'' F_GWJE1,'' F_QDCB1,'' F_YDJE2,'' F_GWJE2,'' F_QDCB2,'' F_YDJE3,'' F_GWJE3,'' F_QDCB3,'' F_YDJE4,'' F_GWJE4,'' F_QDCB4,'' F_YDJE5,'' F_GWJE5,'' F_QDCB5,'' F_YDJE6,'' F_GWJE6,'' F_QDCB6,'' F_YDJE7,'' F_GWJE7,'' F_QDCB7,'' F_YDJE8,'' F_GWJE8,'' F_QDCB8,'' F_YDJE9,'' F_GWJE9,'' F_QDCB9,'' F_YDJE10,'' F_GWJE10,'' F_QDCB10,
'' F_YDJE11,'' F_GWJE11,'' F_QDCB11,'' F_YDJE12,'' F_GWJE12,'' F_QDCB12 
END
GO



DROP PROC SP_SDB_WLMXCX_90009
GO

CREATE PROC [SP_SDB_WLMXCX_90009]
(
@KSRQ VARCHAR(40),
@JSRQ VARCHAR(40),
@GSID VARCHAR(40),
@KH   VARCHAR(40),
@USERID varchar(40)
)
AS 
BEGIN
--往来明细查询

--EXEC SP_SDB_WLMXCX_90009 '20190101','20190131','','',''
--SELECT  '33' F_GSID,'' F_KH,'' F_SYB,'' F_DQ,'' F_BM,'' F_RQ,'' F_FHSL,'' F_FHJE,'' F_HKJE
CREATE TABLE #TEMP
(
F_GSID VARCHAR(40),
F_KH   VARCHAR(40),
F_SYB  VARCHAR(40),
F_DQ   VARCHAR(40),
F_BM   VARCHAR(40),
F_RQ   VARCHAR(40),
F_FHSL DECIMAL(20,2),
F_FHJE DECIMAL(20,2),
F_HKJE DECIMAL(20,2)
)

INSERT INTO  #TEMP(F_GSID , F_KH   ,F_SYB  ,F_DQ   ,F_BM   ,F_RQ   ,F_FHSL ,F_FHJE ,F_HKJE)
SELECT YXERPFH_GSID,YXERPFH_KH,YXERPFH_YXSYB,YXERPFH_YXPQ,YXERPFH_YXBSC,YXERPFH_YWRQ,0 F_SL,YXERPFH_JE,0 F_HKJE 
FROM YXERPFH 
WHERE (YXERPFH_YWRQ BETWEEN @KSRQ AND @JSRQ) AND (YXERPFH_GSID=@GSID OR @GSID='') AND (YXERPFH_KH=@KH OR @KH='')
UNION ALL
SELECT YXRKD_GSID,YXRKD_KH,YXRKD_SYB,YXPQBM_PQNM,YXRKD_BMBH,YXRKD_SKRQ,0 F_SL,0 F_FHJE,YXRKD_JE F_HKJE
FROM YXRKD 
LEFT JOIN YXPQBM ON YXPQBM_BMNM=YXRKD_BMBH 
WHERE  (YXRKD_SKRQ BETWEEN @KSRQ AND @JSRQ) AND (YXRKD_GSID=@GSID OR @GSID='') AND (YXRKD_KH=@KH OR @KH='')


SELECT LSBZDW_DWMC F_GSID , YXKHZD_KHMC F_KH   ,YXSYB_SYBMC F_SYB  ,YXPQZD_PQMC F_DQ   ,YXBMZD_BMMC F_BM   ,F_RQ   ,F_FHSL ,F_FHJE ,F_HKJE  FROM 
#TEMP LEFT JOIN LSBZDW ON LSBZDW_DWBH=F_GSID
LEFT JOIN YXKHZD ON YXKHZD_NM=F_KH
LEFT JOIN YXSYB ON YXSYB_NM=F_SYB
LEFT JOIN YXPQZD ON YXPQZD_NM=F_DQ
LEFT JOIN YXBMZD ON YXBMZD_NM=F_BM



END

GO







DROP PROCEDURE [SP_SD_DDGL_90011] 
GO


CREATE PROCEDURE [SP_SD_DDGL_90011]  
 -- Add the parameters for the stored procedure here  
 @KSRQ VARCHAR(10),  
 @JSRQ VARCHAR(10),  
 --@YWY VARCHAR(40),  
 @DDBH VARCHAR(30),  
 @KH VARCHAR(40),  
 @DDZT VARCHAR(10),  
 @YWLX VARCHAR(20),  
 @ZDR VARCHAR(20),  
 @HTLX VARCHAR(2),  
 @BM VARCHAR(40),  
 @YHTH VARCHAR(20),  
 @HTLXCX VARCHAR(2),  
 @LSBZDW VARCHAR(10),  
 @YKH VARCHAR(100),  
 @SHBZ VARCHAR(1),  
 @JC VARCHAR(50),  
 @USERID VARCHAR(50)  
AS  
BEGIN  
 -- SET NOCOUNT ON added to prevent extra result sets from  
 -- interfering with SELECT statements.  
 SET NOCOUNT ON;  
  
 CREATE TABLE #DDGL  
  (YXDDSQ_GSID VARCHAR(10),  
  YXDDSQ_SHDH VARCHAR(50),  
  YXDZZD_MC VARCHAR(200),  
  YXDDSQ_SHXM VARCHAR(100),  
  LSBZDW_DWMC VARCHAR(50),  
  YXDDSQ_LSBH VARCHAR(40),  
  YXDDSQ_KHBH_BH VARCHAR(40),    
  YXDDSQ_KHBH_MC VARCHAR(100),    
  YXDDSQ_RYBH_MC VARCHAR(50),  
  YXDDSQ_ZJE decimal(16,2),  
  YXDDSQ_DDRQ VARCHAR(20),  
  YXDDSQ_DJBH VARCHAR(20),  
  SHOUDKH VARCHAR(100),/*售达客户*/  
  YXDDSQ_SHBZ VARCHAR(100),  
  YXDDSQ_DDZT VARCHAR(20),  
  YSFS VARCHAR(20),  
  YWLX VARCHAR(20),  
  DDLX VARCHAR(20),  
  SONGDKH VARCHAR(100),/*送达客户*/  
  SPKH VARCHAR(100),/*收票客户*/  
     YXBMZD_BMMC VARCHAR(50),  
  KFKH VARCHAR(100),/*付款客户*/  
  YWY VARCHAR(50),/*业务员*/  
  HTLX VARCHAR(20),  
  SHRBZLXR VARCHAR(200),/*收货地址备注*/  
  JHDD VARCHAR(200),  
  YXDDSQ_ZDR VARCHAR(40),  
  YXDDSQ_BZ VARCHAR(200),  
  HTZ VARCHAR(50),  
  SHR VARCHAR(100),/*收货人*/  
  KHZZQK VARCHAR(100),/*客户资质情况备注*/  
  JBRBH VARCHAR(40),/*经办人编号*/  
  YHTH VARCHAR(200),/*原合同编号*/  
  CKDZ VARCHAR(400),/*仓库注册地址*/  
  GSZCDZ VARCHAR(200),/*公司注册地址*/  
  GFSQR VARCHAR(40),/*供方授权人*/  
  XFSQR VARCHAR(40),/*需方授权人*/  
  CYR VARCHAR(100),/*承运人*/  
  SJJBR VARCHAR(50),/*实际经办人*/  
  YWLXR VARCHAR(40), /*业务联系人*/  
  YXDDSQ_BMNM VARCHAR(20),  
  YXDDSQMX_JC VARCHAR(200),  
  YXDDSQMX_SL decimal(16,2) ,  
  YXDDSQMX_DJ decimal(16,2),  
  YXDDSQMX_CPDJ decimal(16,2),  
  YXDDSQMX_JE decimal(16,2),  
  YXDDSQMX_ZKE decimal(16,2),  
  YXDDSQMX_UF2 VARCHAR(50),  
  HSJE decimal(16,2),  
  YXDDSQMX_UF3  VARCHAR(200),  
  YXDDSQ_C03 VARCHAR(100),  
  YXDDSQ_KHMC VARCHAR(100),  
  YXDDSQMX_FLBH VARCHAR(40), --新增分录编号排序20180403 YC  
  YXDDSQMX_UF8 DECIMAL(16,2), --新增重量字段20190603
  YXDDSQMX_UF9 DECIMAL(16,2)--新增体积字段20190603
  )  
  
  
INSERT INTO #DDGL(  
  YXDDSQ_GSID,  
        YXDDSQ_SHDH,  
  YXDZZD_MC ,  
  YXDDSQ_SHXM ,  
  LSBZDW_DWMC ,  
  YXDDSQ_LSBH ,  
  YXDDSQ_KHBH_BH ,    
  YXDDSQ_KHBH_MC,    
  YXDDSQ_RYBH_MC ,  
  YXDDSQ_ZJE ,  
  YXDDSQ_DDRQ ,  
  YXDDSQ_DJBH ,  
  SHOUDKH ,/*售达客户*/  
  YXDDSQ_SHBZ ,  
  YXDDSQ_DDZT,  
  YSFS ,  
  YWLX ,  
  DDLX ,  
  SONGDKH ,/*送达客户*/  
  SPKH ,/*收票客户*/  
     YXBMZD_BMMC ,  
  KFKH ,/*付款客户*/  
  YWY ,/*业务员*/  
  HTLX ,  
  SHRBZLXR ,/*收货地址备注*/  
  JHDD ,  
  YXDDSQ_ZDR,  
  YXDDSQ_BZ,  
  HTZ ,  
  SHR ,/*收货人*/  
  KHZZQK ,/*客户资质情况备注*/  
  JBRBH ,/*经办人编号*/  
  YHTH ,/*原合同编号*/  
  CKDZ,/*仓库注册地址*/  
  GSZCDZ ,/*公司注册地址*/  
  GFSQR ,/*供方授权人*/  
  XFSQR,/*需方授权人*/  
  CYR ,/*承运人*/  
  SJJBR ,/*实际经办人*/  
  YWLXR, /*业务联系人*/  
  YXDDSQ_BMNM ,  
  YXDDSQMX_JC ,  
  YXDDSQMX_SL  ,  
  YXDDSQMX_DJ ,  
  YXDDSQMX_CPDJ ,  
  YXDDSQMX_JE,  
  YXDDSQMX_ZKE ,  
  YXDDSQMX_UF2 ,  
  HSJE ,  
  YXDDSQMX_UF3 ,  
  YXDDSQ_C03 ,  
  YXDDSQ_KHMC,  
  YXDDSQMX_FLBH,
  YXDDSQMX_UF8,
  YXDDSQMX_UF9)  
 SELECT  
  YXDDSQ_GSID,  
  YXDDSQ_SHDH,  
  YXDDSQ_DZDZ,  
  YXDDSQ_SHXM,  
  YXDDSQ_GSID,  
  YXDDSQ_LSBH,  
  YXDDSQ_KHBH,    
  YXDDSQ_KHBH,    
  YXDDSQ_GFSQR,  
  YXDDSQ_ZJE,  
  YXDDSQ_DDRQ,  
  YXDDSQ_DJBH,  
  YXDDSQ_KHBH,/*售达客户*/  
  YXDDSQ_SHBZ,  
  CASE YXDDSQ_DDZT WHEN '0' THEN '制单' WHEN '1' THEN '提交' WHEN '2' THEN '已生成ERP订单' WHEN '3' THEN '已发货通知'   
  WHEN '4' THEN '已出库' WHEN '5' THEN '已开票' END  YXDDSQ_DDZT,  
  YXDDSQ_YSFS,  
  YXDDSQ_UF16,  
  CASE YXDDSQ_C01 WHEN '1' THEN '普通订单' WHEN '2' THEN '直调订单' END DDLX,  
  YXDDSQ_KHBH,/*送达客户*/  
  YXDDSQ_KHBH,/*收票客户*/  
     YXDDSQ_BMNM,  
  YXDDSQ_KHBH,/*付款客户*/  
  YXDDSQ_GFSQR,/*业务员*/  
  CASE YXDDSQ_UF1 WHEN '1' THEN '传真件' WHEN '2' THEN '原件' WHEN '3' THEN '原件换' WHEN '4' THEN '原件(BG)'END  HTLX,  
  YXDDSQ_UF4 SHRBZLXR,/*收货地址备注*/  
  YXDDSQ_UF17 JHDD,  
  YXDDSQ_ZDR,YXDDSQ_BZ,  
  CASE YXDDSQ_UF2 WHEN '1' THEN '有' WHEN '0' THEN '无'  END   HTZ,  
  YXDDSQ_SHXM,/*收货人*/  
  YXDDSQ_UF8 KHZZQK,/*客户资质情况*/  
  YXDDSQ_GFSQR,/*经办人编号*/  
  YXDDSQ_HTH YHTH,/*原合同编号*/  
  YXDDSQ_UF10 CKDZ,/*仓库注册地址*/  
  YXDDSQ_UF9 GSZCDZ,/*公司注册地址*/  
  YXDDSQ_RYBH,/*供方授权人*/  
  YXDDSQ_XFSQR,/*需方授权人*/  
  YXDDSQ_UF15,/*承运人*/  
  YXDDSQ_GFSQR,/*实际经办人*/  
  YXDDSQ_DLS, /*业务联系人*/  
  YXDDSQ_BMNM,  
  YXDDSQMX_UF1+' || '+YXDDSQMX_GG YXDDSQMX_JC,  
  YXDDSQMX_SL,  
  YXDDSQMX_DJ,  
  YXDDSQMX_CPDJ,  
  YXDDSQMX_JE,  
  YXDDSQMX_ZKE,  
  YXDDSQMX_UF2,  
  YXDDSQMX_SL*YXDDSQMX_DJ HSJE,  
  YXDDSQMX_UF3 ,  
  YXDDSQ_C03,  
  YXDDSQ_KHMC,  
  YXDDSQMX_FLBH ,
  YXDDSQMX_UF8,
  YXDDSQMX_UF9 
  FROM yxddsq WITH (NOLOCK),YXDDSQMX WITH (NOLOCK)  
  WHERE YXDDSQ_LSBH=YXDDSQMX_LSBH  
  AND  (YXDDSQ_DDRQ>=@KSRQ  OR ISNULL(@KSRQ,'')='')  
  AND (YXDDSQ_DDRQ<=@JSRQ OR ISNULL(@JSRQ,'')='')  
  AND (YXDDSQ_DJBH LIKE '%'+@DDBH+'%' OR ISNULL(@DDBH,'')='')  
  AND (YXDDSQ_KHBH=@KH OR ISNULL(@KH,'')='')  
  AND (YXDDSQ_DDZT=@DDZT OR ISNULL(@DDZT,'')='' OR @DDZT='9')  
  AND (YXDDSQ_UF16 LIKE '%'+@YWLX+'%' OR ISNULL(@YWLX,'')='')   
  AND (YXDDSQ_ZDR LIKE  '%'+@ZDR+'%' OR ISNULL(@ZDR,'')='')  
  AND (YXDDSQ_BMNM=@BM OR ISNULL(@BM,'')='')  
  AND (YXDDSQ_HTH LIKE '%'+@YHTH+'%' OR ISNULL(@YHTH,'')='')  
  AND (YXDDSQ_UF1=@HTLXCX OR @HTLXCX='0' OR ISNULL(@HTLXCX,'')='')  
  AND (YXDDSQ_KHMC LIKE '%'+@YKH+'%' OR ISNULL(@YKH,'')='')  
  AND (YXDDSQ_SHBZ=@SHBZ OR ISNULL(@SHBZ,'')='' OR @SHBZ='4')  
  AND ((YXDDSQMX_UF1 LIKE '%'+@JC+'%' OR ISNULL(@JC,'')='') OR (YXDDSQMX_GG LIKE '%'+@JC+'%' OR ISNULL(@JC,'')=''))  
    
  
  
 UPDATE #DDGL SET #DDGL.YXDZZD_MC=YXDZZD.YXDZZD_MC FROM YXDZZD WHERE YXDZZD_NM=#DDGL.YXDZZD_MC;  
 UPDATE #DDGL SET #DDGL.LSBZDW_DWMC=LSBZDW.LSBZDW_DWMC FROM LSBZDW WHERE #DDGL.LSBZDW_DWMC=LSBZDW.LSBZDW_DWBH;  
 UPDATE #DDGL SET #DDGL.YXDDSQ_KHBH_BH=YXKHZD_KHBH FROM YXKHZD WHERE YXKHZD_NM=YXDDSQ_KHBH_BH  
 UPDATE #DDGL SET #DDGL.YXDDSQ_KHBH_MC=YXKHZD_KHMC FROM YXKHZD WHERE YXKHZD_NM=YXDDSQ_KHBH_MC;  
 UPDATE #DDGL SET #DDGL.YXDDSQ_RYBH_MC=YXRYZD_RYXM FROM YXRYZD WHERE YXRYZD_NM=YXDDSQ_RYBH_MC;  
 UPDATE #DDGL SET #DDGL.SHOUDKH=YXKHZD_KHMC FROM YXKHZD WHERE YXKHZD_NM=SHOUDKH;  
 UPDATE #DDGL SET #DDGL.YSFS=YXYSFS_MC FROM YXYSFS WHERE YXYSFS_BH=YSFS;  
 UPDATE #DDGL SET #DDGL.YWLX=YXDDYWLX_MC FROM YXDDYWLX WHERE YXDDYWLX_NM=YWLX;  
 UPDATE #DDGL SET #DDGL.SONGDKH=YXKHZD_KHMC FROM YXKHZD WHERE YXKHZD_NM=SONGDKH;  
 UPDATE #DDGL SET #DDGL.SPKH=YXKHZD_KHMC FROM YXKHZD WHERE YXKHZD_NM=SPKH;  
 UPDATE #DDGL SET #DDGL.YXBMZD_BMMC=YXBMZD.YXBMZD_BMMC FROM YXBMZD WHERE YXBMZD.YXBMZD_NM=#DDGL.YXBMZD_BMMC;  
 UPDATE #DDGL SET #DDGL.KFKH=YXKHZD_KHMC FROM YXKHZD WHERE YXKHZD_NM=KFKH  
 UPDATE #DDGL SET #DDGL.YWY=YXRYQYDM_MC FROM YXRYQYDM WHERE YXRYQYDM_BH=YWY;  
 UPDATE #DDGL SET #DDGL.SHR=MC FROM VW_KHSHR WHERE  nm=SHR;  
 UPDATE #DDGL SET #DDGL.JBRBH=YXRYZD_RYBH FROM YXRYZD WHERE YXRYZD_NM=JBRBH;  
 UPDATE #DDGL SET #DDGL.GFSQR=YXRYZD_RYXM FROM YXRYZD WHERE YXRYZD_NM=GFSQR;  
 UPDATE #DDGL SET #DDGL.XFSQR=YXMBRYEX_MC FROM YXMBRYEX WHERE YXMBRYEX_SFZ=XFSQR;  
 UPDATE #DDGL SET #DDGL.CYR=YXRYZD_RYXM FROM YXRYZD WHERE YXRYZD_NM=CYR;  
 UPDATE #DDGL SET #DDGL.SJJBR=YXRYZD_RYXM FROM YXRYQYDM,YXRYZD WHERE YXRYQYDM_BH=SJJBR AND YXRYQYDM_YWRY=YXRYZD_NM;  
 UPDATE #DDGL SET #DDGL.YWLXR=YXKHLXR_MC FROM V_YXKHLXR YWLXR WHERE YWLXR.YXKHLXR_ID=YWLXR;  
  
  
  
 SELECT * FROM #DDGL  
 WHERE  (LSBZDW_DWMC LIKE '%'+@LSBZDW+'%' OR ISNULL(@LSBZDW,'')='')  
 AND YXDDSQ_GSID IN(SELECT AO_DATA FROM GSPUSER , GSPAURESULT WHERE OWNERID=GSPUSER.ID   
AND AO_ID='GSP_SCF_LSBZDW'   
AND CODE=@USERID )  
AND   KFKH IN (SELECT SDUSERYWZZ_DWBH FROM SDUSERYWZZ WHERE SDUSERYWZZ_USERID=@USERID)
   ORDER BY YXDDSQ_DJBH DESC,YXDDSQMX_FLBH  
END






GO


DROP  PROC [SP_FH_XSTDMX_90012]
GO

CREATE PROC .[SP_FH_XSTDMX_90012]
@GSID VARCHAR(MAX),--销售公司
@QDLX VARCHAR(MAX),--渠道类型
@KSRQ VARCHAR(8),--开始日期
@JSRQ VARCHAR(8),--结束日期
@WLBH VARCHAR(MAX),--产品
@HSQY VARCHAR(MAX),--区域
@GFSQR VARCHAR(MAX),--供方授权人
@FYFS VARCHAR(MAX),--发运方式
@SFTZ VARCHAR(1),--是否包含调整数据
@KHBH VARCHAR(MAX),--商业公司
@USERID VARCHAR(20)
--@SFLX CHAR(1)--是否包含流向
AS
BEGIN
	set @GSID=replace(replace(@GSID,'(',''),')','')   
	set @QDLX=replace(replace(@QDLX,'(',''),')','') 
	set @HSQY=replace(replace(@HSQY,'(',''),')','')
	set @WLBH=replace(replace(@WLBH,'(',''),')','')
	set @GFSQR=replace(replace(@GFSQR,'(',''),')','')
	set @FYFS=replace(replace(@FYFS,'(',''),')','')
	set @KHBH=replace(replace(@KHBH,'(',''),')','')
	

	SELECT * INTO #YXERPFH FROM YXERPFH
	where (YXERPFH_YWRQ BETWEEN @KSRQ AND @JSRQ)
 AND (YXERPFH_GSID IN (select * from SP_YX_Split(@GSID,','))  OR ISNULL(@GSID,'')='')
 AND (YXERPFH_C11 IN (select * from SP_YX_Split(@QDLX,','))  OR ISNULL(@QDLX,'')='')
 AND (YXERPFH_ERPBMmc IN (select * from SP_YX_Split(@HSQY,','))  OR ISNULL(@HSQY,'')='')
 --AND (YXWLZD_NM IN (select * from SP_YX_Split(@WLBH,','))  OR ISNULL(@WLBH,'')='')
 AND (YXERPFH_c6 IN (select * from SP_YX_Split(@GFSQR,','))  OR ISNULL(@GFSQR,'')='')
 AND (YXERPFH_UF6 IN (select * from SP_YX_Split(@FYFS,','))  OR ISNULL(@FYFS,'')='')
 AND (YXERPFH_KH IN (select * from SP_YX_Split(@KHBH,','))  OR ISNULL(@KHBH,'')='')
 --AND ISNULL(YXERPFH_drbs,'')='' 
-- and YXERPFH_gsid<>'01006'
 AND (YXERPFH_YXSYB IN(SELECT AO_DATA FROM GSPAURESULT  
LEFT JOIN GSPUSER ON GSPUser.ID=OWNERID 
WHERE BIZOBJID='YX_SJQX' AND AO_ID='YXSJSYBQX'  
AND GSPUSER.CODE=@USERID)  
OR exists(SELECT 1 FROM GSPAURESULT  
LEFT JOIN GSPUSER ON GSPUser.ID=OWNERID 
WHERE BIZOBJID='YX_SJQX' AND AO_ID='YXSJSYBQX'  
AND GSPUSER.CODE=@USERID
AND AO_DATA='*') )


IF @SFTZ='1' --包含
BEGIN

SELECT LSBZDW_DWMC YXERPFH_ERPGSBH,YXWWXT_MC,YXERPFH_YWRQ,YXERPFH_CRMDDH,YXERPFH_ERPFHDH,YXERPFH_ERPDDH,'' HYDH,
YXERPFH_C9, YXDDYWLX_MC, YXERPFH_ERPBM,YXERPFH_ERPBMMC,YXBMZD_BMBH,yxbmzd_bmmc,
YXERPFH_ERPKH, CASE WHEN LEN(YXERPFH_KH)=9 THEN YXERPFH_KH ELSE kh.YXKHZD_KHBH END KHBH,CASE WHEN ISNULL(YXKHZD_KHMC,'')='' THEN YXERPFH_ERPKHMC ELSE YXKHZD_KHMC END KHMC,
YXERPFH_CPBH,CASE WHEN ISNULL(YXERPFH_YXCPBH,'')='' THEN YXERPFH_CPBH ELSE YXWLZD_WLBH END YXERPFH_YXCPBH,CASE WHEN ISNULL(YXERPFH_YXCPBH,'')='' THEN YXERPFH_ERPCPMC ELSE YXWLZD_WLMC END YXWLZD_WLMC,YXWLZD_TYM, YXWLZD_GGXH, YXCPXL_MC ,YXCPLB_MC ,ERPJLDW_MC, YXERPFH_SL/NULLIF(YXWLZD_BZDWXS,0) YXERPFH_SL,YXWLZD_HYTJGG,YXERPFH_SL ZXDWSL,--convert(decimal(38, 2),YXERPFH_DJ/YXWLZD_BZDWXS) 
YXERPFH_DJ,YXERPFH_JE, YXWLZD_UFCPJC,
CASE  WHEN YXERPFH_C2='ZZK1' THEN '折扣类型1' WHEN YXERPFH_C2='ZZK2' THEN '折扣类型R' ELSE '' END YXERPFH_C2,
case  WHEN YXERPFH_C2='ZZK1' THEN YXERPFH_U2 WHEN YXERPFH_C2='ZZK2' THEN YXERPFH_UF1  END YXERPFH_U2 ,--折扣类型不同,显示字段不同
YXERPFH_U3 ,YXERPFH_U4 ,YXERPFH_SL/NULLIF(YXWLZD_BZDWXS,0) YXERPFH_U5 ,YXERPFH_DJ*NULLIF(YXWLZD_BZDWXS,0) YXERPFH_U1 ,YXERPFH_YSL ,
YXERPFH_GFLXR ,YXERPFH_GFLXRMC , YXRYQYDM_BH ,YXRYQYDM_MC ,YXERPFH_XFLXR , 
YXERPFH_XFLXRMC ,DLS.YXKHLXR_BH DLSBH,DLS.YXKHLXR_MC DLSMC, YXERPFH_C7 ,YXERPFH_C8 ,
GFSQR.YXRYZD_RYBH GFSQRBH, GFSQR.YXRYZD_RYXM GFSQRMC,YXERPFH_XFSQR ,YXERPFH_XFSQRMC , 
--XFSQR.YXMBRYEX_MC XFSQRMC,
YXERPFH_YXXFSQR XFSQRMC,
YXERPFH_ERPRY , YXERPFH_ERPRYMC , JBR.YXRYZD_RYBH JBRBH,JBR.YXRYZD_RYXM JBRMC,
 '' FPRQ,'' FPBH , '' YJLX, YXERPFH_UF13 ,
YXERPFH_UF11 ,YXERPFH_UF6,YXERPFH_UF7,YXERPFH_UF8, YXERPFH_ZBGPH,YXERPFH_C12,YXERPFH_ZSJYF,YXERPFH_C13,YXERPFH_ZTHYY, 
YXERPFH_ZTHSL_KH,YXERPFH_ZHHBZSL,YXERPFH_ZSJPSSL,YXERPFH_ZGHBZFY, YXERPFH_ZDBSH,YXERPFH_ZZAFEI,YXERPFH_ZBAOSH,
YXERPFH_ZZHONGL, YXERPFH_C14,YXERPFH_ZYUNF,YXERPFH_ZBEIZ,YXERPFH_C1,YXERPFH_ERPFHHH,YXERPFH_JE_BAK,YXERPFH_PCH
 from #YXERPFH
 left JOIN YXKHZD KH ON KH.YXKHZD_NM=YXERPFH_KH
 left JOIN yxbmzd ON yxbmzd_nm=YXERPFH_YXBSC
 left JOIN YXDDYWLX ON YXDDYWLX_NM=YXERPFH_C11
 left JOIN YXWLZD ON YXWLZD_NM=YXERPFH_YXCPBH
 left JOIN VW_ERPJLDW ON ERPJLDW_NM=YXWLZD_JLDW
 left JOIN yxryqydm ON yxryqydm.YXRYQYDM_BH=YXERPFH_YXGFLXR
 left JOIN V_YXKHLXR DLS ON DLS.YXKHLXR_BH=YXERPFH_YXXFLXR
 left JOIN YXRYZD GFSQR ON GFSQR.YXRYZD_NM=YXERPFH_C6

 left JOIN YXRYZD JBR ON JBR.YXRYZD_NM=YXERPFH_YXYWY
 left JOIN YXCPXL ON YXCPXL_NM=YXWLZD_CPXL
 left JOIN YXCPLB ON YXCPLB.YXCPLB_NM=YXWLZD_WLLB
 left JOIN yxdqzd ON YXDQZD.YXDQZD_DQBH=KH.YXKHZD_DQID
 left JOIN YXWWXT ON YXWWXT.YXWWXT_BH=YXERPFH_WWXT
 LEFT JOIN LSBZDW on LSBZDW_DWBH=YXERPFH_GSID
 where (YXERPFH_YWRQ BETWEEN @KSRQ AND @JSRQ)
 --AND (YXERPFH_GSID IN (select * from SP_YX_Split(@GSID,','))  OR ISNULL(@GSID,'')='')
 --AND (YXERPFH_C11 IN (select * from SP_YX_Split(@QDLX,','))  OR ISNULL(@QDLX,'')='')

 -- AND (YXERPFH_ERPBM IN (select * from SP_YX_Split(@HSQY,','))  OR ISNULL(@HSQY,'')='')
 AND (YXWLZD_NM IN (select * from SP_YX_Split(@WLBH,','))  OR ISNULL(@WLBH,'')='')
  AND YXERPFH_KH IN (SELECT SDUSERYWZZ_DWBH FROM SDUSERYWZZ WHERE SDUSERYWZZ_USERID=@USERID)
 --AND (YXERPFH_c6 IN (select * from SP_YX_Split(@GFSQR,','))  OR ISNULL(@GFSQR,'')='')
 --AND (YXERPFH_UF6 IN (select * from SP_YX_Split(@FYFS,','))  OR ISNULL(@FYFS,'')='')
 --AND (YXERPFH_KH IN (select * from SP_YX_Split(@KHBH,','))  OR ISNULL(@KHBH,'')='')
-- AND (YXERPFH_YXSYB IN(SELECT AO_DATA FROM GSPAURESULT  
--LEFT JOIN GSPUSER ON GSPUser.ID=OWNERID 
--WHERE BIZOBJID='YX_SJQX' AND AO_ID='YXSJSYBQX'  
--AND GSPUSER.CODE=@USERID)  
--OR exists(SELECT 1 FROM GSPAURESULT  
--LEFT JOIN GSPUSER ON GSPUser.ID=OWNERID 
--WHERE BIZOBJID='YX_SJQX' AND AO_ID='YXSJSYBQX'  
--AND GSPUSER.CODE=@USERID
--AND AO_DATA='*') )

order by YXERPFH_YWRQ
 END
 
 IF @SFTZ='2' --调整
BEGIN

SELECT LSBZDW_DWMC YXERPFH_ERPGSBH,YXWWXT_MC,YXERPFH_YWRQ,YXERPFH_CRMDDH,YXERPFH_ERPFHDH,YXERPFH_ERPDDH,'' HYDH,
YXERPFH_C9, YXDDYWLX_MC, YXERPFH_ERPBM,YXERPFH_ERPBMMC,YXBMZD_BMBH,yxbmzd_bmmc,
YXERPFH_ERPKH, CASE WHEN LEN(YXERPFH_KH)=9 THEN YXERPFH_KH ELSE kh.YXKHZD_KHBH END KHBH,YXERPFH_ERPKHMC KHMC,
YXERPFH_CPBH,CASE WHEN ISNULL(YXERPFH_YXCPBH,'')='' THEN YXERPFH_CPBH ELSE YXWLZD_WLBH END YXERPFH_YXCPBH,CASE WHEN ISNULL(YXERPFH_YXCPBH,'')='' THEN YXERPFH_ERPCPMC ELSE YXWLZD_WLMC END YXWLZD_WLMC,YXWLZD_TYM, YXWLZD_GGXH, YXCPXL_MC ,YXCPLB_MC ,ERPJLDW_MC, YXERPFH_SL/NULLIF(YXWLZD_BZDWXS,0) YXERPFH_SL,YXWLZD_HYTJGG,YXERPFH_SL ZXDWSL, --convert(decimal(38, 2),YXERPFH_DJ/YXWLZD_BZDWXS) 
YXERPFH_DJ,YXERPFH_JE, YXWLZD_UFCPJC,
CASE  WHEN YXERPFH_C2='ZZK1' THEN '折扣类型1' WHEN YXERPFH_C2='ZZK2' THEN '折扣类型R' ELSE '' END YXERPFH_C2,
CASE  WHEN YXERPFH_C2='ZZK1' THEN YXERPFH_U2 WHEN YXERPFH_C2='ZZK2' THEN YXERPFH_UF1  END YXERPFH_U2 ,--折扣类型不同,显示字段不同
YXERPFH_U3 ,YXERPFH_U4 ,YXERPFH_SL/NULLIF(YXWLZD_BZDWXS,0) YXERPFH_U5 ,YXERPFH_DJ*NULLIF(YXWLZD_BZDWXS,0) YXERPFH_U1 ,YXERPFH_YSL ,
YXERPFH_GFLXR ,YXERPFH_GFLXRMC , YXRYQYDM_BH ,YXRYQYDM_MC ,YXERPFH_XFLXR , 
YXERPFH_XFLXRMC ,DLS.YXKHLXR_BH DLSBH,DLS.YXKHLXR_MC DLSMC, YXERPFH_C7 ,YXERPFH_C8 ,
GFSQR.YXRYZD_RYBH GFSQRBH, GFSQR.YXRYZD_RYXM GFSQRMC,YXERPFH_XFSQR ,YXERPFH_XFSQRMC , 
--XFSQR.YXMBRYEX_MC XFSQRMC,
YXERPFH_YXXFSQR XFSQRMC,
YXERPFH_ERPRY , YXERPFH_ERPRYMC , JBR.YXRYZD_RYBH JBRBH,JBR.YXRYZD_RYXM JBRMC,
 '' FPRQ,'' FPBH , '' YJLX, YXERPFH_UF13 ,
YXERPFH_UF11 ,YXERPFH_UF6,YXERPFH_UF7,YXERPFH_UF8, YXERPFH_ZBGPH,YXERPFH_C12,YXERPFH_ZSJYF,YXERPFH_C13,YXERPFH_ZTHYY, 
YXERPFH_ZTHSL_KH,YXERPFH_ZHHBZSL,YXERPFH_ZSJPSSL,YXERPFH_ZGHBZFY, YXERPFH_ZDBSH,YXERPFH_ZZAFEI,YXERPFH_ZBAOSH,
YXERPFH_ZZHONGL, YXERPFH_C14,YXERPFH_ZYUNF,YXERPFH_ZBEIZ,YXERPFH_C1,YXERPFH_ERPFHHH,YXERPFH_JE_BAK,YXERPFH_PCH
 FROM #YXERPFH
 LEFT JOIN YXKHZD KH ON KH.YXKHZD_NM=YXERPFH_KH
 LEFT JOIN yxbmzd ON yxbmzd_nm=YXERPFH_YXBSC
 LEFT JOIN YXDDYWLX ON YXDDYWLX_NM=YXERPFH_C11
 LEFT JOIN YXWLZD ON YXWLZD_NM=YXERPFH_YXCPBH
 LEFT JOIN VW_ERPJLDW ON ERPJLDW_NM=YXWLZD_JLDW
 LEFT JOIN yxryqydm ON yxryqydm.YXRYQYDM_BH=YXERPFH_YXGFLXR
 LEFT JOIN V_YXKHLXR DLS ON DLS.YXKHLXR_BH=YXERPFH_YXXFLXR
 LEFT JOIN YXRYZD GFSQR ON GFSQR.YXRYZD_NM=YXERPFH_C6

 LEFT JOIN YXRYZD JBR ON JBR.YXRYZD_NM=YXERPFH_YXYWY
 LEFT JOIN YXCPXL ON YXCPXL_NM=YXWLZD_CPXL
 LEFT JOIN YXCPLB ON YXCPLB.YXCPLB_NM=YXWLZD_WLLB
 LEFT JOIN yxdqzd ON YXDQZD.YXDQZD_DQBH=KH.YXKHZD_DQID
 LEFT JOIN YXWWXT ON YXWWXT.YXWWXT_BH=YXERPFH_WWXT
 LEFT JOIN LSBZDW ON LSBZDW_DWBH=YXERPFH_GSID
 WHERE (YXERPFH_YWRQ BETWEEN @KSRQ AND @JSRQ)
 --AND (YXERPFH_GSID IN (select * from SP_YX_Split(@GSID,','))  OR ISNULL(@GSID,'')='')
 --AND (YXERPFH_C11 IN (select * from SP_YX_Split(@QDLX,','))  OR ISNULL(@QDLX,'')='')
 --AND (YXERPFH_ERPBM IN (select * from SP_YX_Split(@HSQY,','))  OR ISNULL(@HSQY,'')='')
 AND (YXWLZD_NM IN (SELECT * FROM SP_YX_Split(@WLBH,','))  OR ISNULL(@WLBH,'')='')
 --AND (YXERPFH_c6 IN (select * from SP_YX_Split(@GFSQR,','))  OR ISNULL(@GFSQR,'')='')
 --AND (YXERPFH_UF6 IN (select * from SP_YX_Split(@FYFS,','))  OR ISNULL(@FYFS,'')='')
 --AND (YXERPFH_KH IN (select * from SP_YX_Split(@KHBH,','))  OR ISNULL(@KHBH,'')='')
 AND ISNULL(YXERPFH_UFLX,'')='1' 
 AND YXERPFH_KH IN (SELECT SDUSERYWZZ_DWBH FROM SDUSERYWZZ WHERE SDUSERYWZZ_USERID=@USERID)

-- AND (YXERPFH_YXSYB IN(SELECT AO_DATA FROM GSPAURESULT  
--LEFT JOIN GSPUSER ON GSPUser.ID=OWNERID 
--WHERE BIZOBJID='YX_SJQX' AND AO_ID='YXSJSYBQX'  
--AND GSPUSER.CODE=@USERID)  
--OR exists(SELECT 1 FROM GSPAURESULT  
--LEFT JOIN GSPUSER ON GSPUser.ID=OWNERID 
--WHERE BIZOBJID='YX_SJQX' AND AO_ID='YXSJSYBQX'  
--AND GSPUSER.CODE=@USERID
--AND AO_DATA='*') )

ORDER BY YXERPFH_YWRQ
 END


 END



 GO



   DROP proc [SP_SDB_JGZCSG_BEFORESAVE]  
  GO       
CREATE proc [SP_SDB_JGZCSG_BEFORESAVE]
(   
 @UserID varchar(40),   
 @BillNo varchar(40)    
)   
as 
/*手工的价格政策保存前存储过程*/
begin

-- RAISERROR ('dddd',16,1) 
--删除价格政策表相关的手工生成的数据
DELETE YXJGZCB FROM  YXJGZCBMX WHERE YXJGZCBMX_ID=@BillNo AND YXJGZCB_ID=YXJGZCBMX_GUID AND YXJGZCB_LY='4'
end

GO








DROP  PROC SP_PLCLJGZC_LS
GO
CREATE PROC SP_PLCLJGZC_LS
(
@CON INT,--分单行数，如果不分单填写也没关系
@FLAG INT --0不分单,1分单
)
AS
BEGIN

--EXEC SP_PLCLJGZC_LS 50,1
/*
SELECT COUNT(*) FROM YXJGZCBMX  16679
SELECT COUNT(*) FROM YXJGZCBM   540
SELECT ROW_NUMBER() OVER(ORDER BY YXJGZCBMX_ID), YXJGZCBMX_ID,COUNT(*) F_CON FROM YXJGZCBMX GROUP BY YXJGZCBMX_ID HAVING COUNT(*)>50
/*
SELECT SUM(F_EXTCON)
 FROM (
 SELECT  YXJGZCBMX_ID,COUNT(*) F_CON,ceiling(cast(COUNT(*) as float)/cast(50 as float))-1 F_EXTCON FROM YXJGZCBMX GROUP BY YXJGZCBMX_ID HAVING COUNT(*)>50
 )A
--drop index YXJGZCB	on YXJGZCB

--SELECT COUNT(*) FROM YXJGZCBMX  16670
--SELECT COUNT(*) FROM YXJGZCBM  536+215
--go
*/
*/
TRUNCATE TABLE  YXJGZCBM 

TRUNCATE TABLE  YXJGZCBMX

INSERT INTO YXJGZCBM(YXJGZCBM_ID,YXJGZCBM_GSID,YXJGZCBM_QDLX,YXJGZCBM_SYB,YXJGZCBM_BM,YXJGZCBM_KHBH,YXJGZCBM_ZCLX,YXJGZCBM_LY)
--销售公司、渠道类型、区域、客户、政策类型、制单人、制单日期,
SELECT NEWID()F_ID, ISNULL(YXJGZCB_GSID,''),ISNULL(YXJGZCB_UFQDLX,''),ISNULL(YXJGZCB_SYB,''),ISNULL(YXJGZCB_BM,''),ISNULL(YXJGZCB_KHBH,''),ISNULL(YXJGZCB_UF_ZCLX,''),ISNULL(YXJGZCB_LY,'')
 FROM YXJGZCB  WHERE YXJGZCB_LY='4' GROUP BY ISNULL(YXJGZCB_GSID,''),ISNULL(YXJGZCB_UFQDLX,''),ISNULL(YXJGZCB_SYB,''),ISNULL(YXJGZCB_BM,''),ISNULL(YXJGZCB_KHBH,''),ISNULL(YXJGZCB_UF_ZCLX,''),ISNULL(YXJGZCB_LY,'')
 


 INSERT INTO YXJGZCBMX(YXJGZCBMX_ID,YXJGZCBMX_FLBH,YXJGZCBMX_GSID,YXJGZCBMX_UFQDLX,YXJGZCBMX_SYB,YXJGZCBMX_BM,YXJGZCBMX_KHBH,YXJGZCBMX_UF_ZCLX,YXJGZCBMX_LY,YXJGZCBMX_GUID,YXJGZCBMX_WLBH,YXJGZCBMX_KPJ, YXJGZCBMX_DJ,YXJGZCBMX_KSRQ,YXJGZCBMX_JSRQ,YXJGZCBMX_XLDX,YXJGZCBMX_SYBZ,YXJGZCBMX_UF_TYM,YXJGZCBMX_UF_SPM,YXJGZCBMX_UF_GG,YXJGZCBMX_UF_JLDW,YXJGZCBMX_UF_SFPD,YXJGZCBMX_DEMO,YXJGZCBMX_UFKPJ2)


SELECT NEWID() F_ID,NEWID() F_FLBH, YXJGZCB_GSID,YXJGZCB_UFQDLX,YXJGZCB_SYB,YXJGZCB_BM,YXJGZCB_KHBH,YXJGZCB_UF_ZCLX,YXJGZCB_LY,YXJGZCB_ID,YXJGZCB_WLBH,YXJGZCB_KPJ, 
                    YXJGZCB_DJ,YXJGZCB_KSRQ,YXJGZCB_JSRQ,YXJGZCB_XLDX,
                    YXJGZCB_SYBZ,YXJGZCB_UF_TYM,YXJGZCB_UF_SPM,YXJGZCB_UF_GG,
					YXJGZCB_UF_JLDW,YXJGZCB_UF_SFPD,
					YXJGZCB_DEMO,YXJGZCB_UFKPJ2 FROM YXJGZCB WHERE YXJGZCB_LY='4'
 IF NOT  EXISTS (select   1   from   syscolumns   where   id=object_id('YXJGZCBMX')   and   name='YXJGZCBMX_IDBAK'  )
 BEGIN
 ALTER TABLE YXJGZCBMX ADD YXJGZCBMX_IDBAK VARCHAR(40)

 END
 
 UPDATE YXJGZCBMX SET YXJGZCBMX_IDBAK=NEWID()
 


 UPDATE YXJGZCBMX SET YXJGZCBMX_ID=YXJGZCBM_ID FROM YXJGZCBM WHERE ISNULL(YXJGZCBM_GSID,'')=ISNULL(YXJGZCBMX_GSID,'') AND ISNULL(YXJGZCBM_QDLX,'')=ISNULL(YXJGZCBMX_UFQDLX,'') AND ISNULL(YXJGZCBM_SYB,'')=ISNULL(YXJGZCBMX_SYB,'') AND ISNULL(YXJGZCBM_BM,'')=ISNULL(YXJGZCBMX_BM,'')
 AND ISNULL(YXJGZCBM_KHBH,'')=ISNULL(YXJGZCBMX_KHBH,'') AND ISNULL(YXJGZCBM_ZCLX,'')=isnull(YXJGZCBMX_UF_ZCLX,'') AND isnull(YXJGZCBM_LY,'')=isnull(YXJGZCBMX_LY,'')

 

 UPDATE YXJGZCBMX SET YXJGZCBMX_FLBH=F_FLBH FROM (  select YXJGZCBMX_IDBAK F_ID,   RIGHT('000000'+CAST(ROW_NUMBER() over(partition by YXJGZCBMX_ID order by YXJGZCBMX_ID desc) AS VARCHAR),4) F_FLBH FROM YXJGZCBMX) LSB WHERE LSB.F_ID=YXJGZCBMX.YXJGZCBMX_IDBAK

 



 
 IF @FLAG=1


 BEGIN --@FLAG=1

 DECLARE @CONERV INT
 DECLARE @TOCON INT
  DECLARE @I INT
   SET @I=1
   DECLARE @J INT
 CREATE TABLE #tmp
 (
 F_BH INT,
 F_LSBH VARCHAR(40),
 F_CON  INT
 )
 INSERT INTO #tmp(F_BH,F_LSBH,F_CON)
  SELECT ROW_NUMBER() OVER(ORDER BY YXJGZCBMX_ID), YXJGZCBMX_ID,COUNT(*) F_CON FROM YXJGZCBMX GROUP BY YXJGZCBMX_ID HAVING COUNT(*)>@CON
  --获取要处理的行数
  SELECT @TOCON=COUNT(*) FROM #tmp
 
 SET @CONERV=@CON --按照多少条分单
 

 DECLARE @LS VARCHAR(40)
 DECLARE @LS1 VARCHAR(40)--存储复制表后的表头流水
 DECLARE @TMPCON INT
 --
 --SELECT ceiling(cast(68 as float)/cast(50 as float))-1
  --SELECT cast(99 as float)/cast(50 as float)
 WHILE @I<=@TOCON
 begin --@I S

 SELECT @LS=F_LSBH,@TMPCON=F_CON FROM #tmp WHERE F_BH=@I

     set @J=1
     WHILE @J<=  ceiling(cast(@TMPCON as float)/cast(@CONERV as float))-1
     begin--@J S
	  SELECT @LS1=NEWID()
     INSERT INTO YXJGZCBM(YXJGZCBM_ID,YXJGZCBM_GSID,YXJGZCBM_QDLX,YXJGZCBM_SYB,YXJGZCBM_BM,YXJGZCBM_KHBH,YXJGZCBM_ZCLX,YXJGZCBM_LY)
     SELECT @LS1 F_ID, YXJGZCBM_GSID,YXJGZCBM_QDLX,YXJGZCBM_SYB,YXJGZCBM_BM,YXJGZCBM_KHBH,YXJGZCBM_ZCLX,YXJGZCBM_LY FROM YXJGZCBM WHERE YXJGZCBM_ID=@LS

     UPDATE YXJGZCBMX SET YXJGZCBMX_ID=@LS1  WHERE  YXJGZCBMX_ID=@LS AND  CAST(YXJGZCBMX_FLBH AS INT)>=@J*@CONERV+1   AND  CAST(YXJGZCBMX_FLBH AS INT)<=(@J+1)*@CONERV

	  UPDATE YXJGZCBMX SET YXJGZCBMX_FLBH=F_FLBH FROM (  select YXJGZCBMX_GUID F_ID,   RIGHT('000000'+CAST(ROW_NUMBER() over( order by YXJGZCBMX_WLBH desc) AS VARCHAR),4) F_FLBH FROM YXJGZCBMX where YXJGZCBMX_ID=@LS1) LSB WHERE LSB.F_ID=YXJGZCBMX.YXJGZCBMX_GUID AND YXJGZCBMX_ID=@LS1

     set @J=@J+1

    end --@J  E

	-- select YXJGZCBMX_GUID F_ID,   RIGHT('000000'+CAST(ROW_NUMBER() over( order by YXJGZCBMX_WLBH desc) AS VARCHAR),4) F_FLBH FROM YXJGZCBMX WHERE YXJGZCBMX_ID='08125116-E29E-46B0-BBCF-83A5D80F6BA4'

	 -- select  YXJGZCBMX_ID,YXJGZCBMX_GUID FROM YXJGZCBMX WHERE YXJGZCBMX_ID='00B4E860-8BD2-4DF7-88EE-C33ED5E109E0' GROUP BY  YXJGZCBMX_GUID

 SET @I=@I+1
 end

 END --@FLAG=1
  



 END



