DELETE FROM SDSYSSQL WHERE SDSYSSQL_ID IN ('GETLISTFILTER','GETLISTCOLUMN')
GO
INSERT INTO SDSYSSQL(SDSYSSQL_ID,SDSYSSQL_SQL,SDSYSSQL_PARAMETER,SDSYSSQL_CODE,SDSYSSQL_TITLE)
VALUES('GETLISTFILTER','SELECT SDSYSFILTER_OBJNAME BH,SUBSTRING(SDSYSFILTER_OBJID,3,LEN(SDSYSFILTER_OBJID)-2) ZD,SUBSTRING(SDSYSFILTER_OBJID,1,1) CZF FROM SDSYSFILTER WHERE SDSYSFILTER_ID=@LISTID AND SDSYSFILTER_OBJID NOT LIKE ''txt%''','@LISTID','SDJ','获取列表过滤条件')
GO
INSERT INTO SDSYSSQL(SDSYSSQL_ID,SDSYSSQL_SQL,SDSYSSQL_PARAMETER,SDSYSSQL_CODE,SDSYSSQL_TITLE)
VALUES('GETLISTCOLUMN','select SDSYSLISTITEM_FIELDNAME ZD from SDSYSLISTITEM where SDSYSLISTITEM_ID=@LISTID AND  SDSYSLISTITEM_FIELDNAME<>''''','@LISTID','SDJ','获取列表列定义')
GO
