
--drop index YXJGZCB	on YXJGZCB
--go

TRUNCATE TABLE  YXJGZCBM 
GO
TRUNCATE TABLE  YXJGZCBMX
GO
INSERT INTO YXJGZCBM(YXJGZCBM_ID,YXJGZCBM_GSID,YXJGZCBM_QDLX,YXJGZCBM_SYB,YXJGZCBM_BM,YXJGZCBM_KHBH,YXJGZCBM_ZCLX,YXJGZCBM_LY)
--销售公司、渠道类型、区域、客户、政策类型、制单人、制单日期,
SELECT NEWID()F_ID, ISNULL(YXJGZCB_GSID,''),ISNULL(YXJGZCB_UFQDLX,''),ISNULL(YXJGZCB_SYB,''),ISNULL(YXJGZCB_BM,''),ISNULL(YXJGZCB_KHBH,''),ISNULL(YXJGZCB_UF_ZCLX,''),ISNULL(YXJGZCB_LY,'')
 FROM YXJGZCB  WHERE YXJGZCB_LY='4' GROUP BY ISNULL(YXJGZCB_GSID,''),ISNULL(YXJGZCB_UFQDLX,''),ISNULL(YXJGZCB_SYB,''),ISNULL(YXJGZCB_BM,''),ISNULL(YXJGZCB_KHBH,''),ISNULL(YXJGZCB_UF_ZCLX,''),ISNULL(YXJGZCB_LY,'')
 GO


 INSERT INTO YXJGZCBMX(YXJGZCBMX_ID,YXJGZCBMX_FLBH,YXJGZCBMX_GSID,YXJGZCBMX_UFQDLX,YXJGZCBMX_SYB,YXJGZCBMX_BM,YXJGZCBMX_KHBH,YXJGZCBMX_UF_ZCLX,YXJGZCBMX_LY,YXJGZCBMX_GUID,YXJGZCBMX_WLBH,YXJGZCBMX_KPJ, YXJGZCBMX_DJ,YXJGZCBMX_KSRQ,YXJGZCBMX_JSRQ,YXJGZCBMX_XLDX,YXJGZCBMX_SYBZ,YXJGZCBMX_UF_TYM,YXJGZCBMX_UF_SPM,YXJGZCBMX_UF_GG,YXJGZCBMX_UF_JLDW,YXJGZCBMX_UF_SFPD,YXJGZCBMX_DEMO,YXJGZCBMX_UFKPJ2)


SELECT NEWID() F_ID,NEWID() F_FLBH, YXJGZCB_GSID,YXJGZCB_UFQDLX,YXJGZCB_SYB,YXJGZCB_BM,YXJGZCB_KHBH,YXJGZCB_UF_ZCLX,YXJGZCB_LY,YXJGZCB_ID,YXJGZCB_WLBH,YXJGZCB_KPJ, 
                    YXJGZCB_DJ,YXJGZCB_KSRQ,YXJGZCB_JSRQ,YXJGZCB_XLDX,
                    YXJGZCB_SYBZ,YXJGZCB_UF_TYM,YXJGZCB_UF_SPM,YXJGZCB_UF_GG,
					YXJGZCB_UF_JLDW,YXJGZCB_UF_SFPD,
					YXJGZCB_DEMO,YXJGZCB_UFKPJ2 FROM YXJGZCB WHERE YXJGZCB_LY='4'

 ALTER TABLE YXJGZCBMX ADD YXJGZCBMX_IDBAK VARCHAR(40)
 GO
 UPDATE YXJGZCBMX SET YXJGZCBMX_IDBAK=NEWID()
 GO


 UPDATE YXJGZCBMX SET YXJGZCBMX_ID=YXJGZCBM_ID FROM YXJGZCBM WHERE ISNULL(YXJGZCBM_GSID,'')=ISNULL(YXJGZCBMX_GSID,'') AND ISNULL(YXJGZCBM_QDLX,'')=ISNULL(YXJGZCBMX_UFQDLX,'') AND ISNULL(YXJGZCBM_SYB,'')=ISNULL(YXJGZCBMX_SYB,'') AND ISNULL(YXJGZCBM_BM,'')=ISNULL(YXJGZCBMX_BM,'')
 AND ISNULL(YXJGZCBM_KHBH,'')=ISNULL(YXJGZCBMX_KHBH,'') AND ISNULL(YXJGZCBM_ZCLX,'')=isnull(YXJGZCBMX_UF_ZCLX,'') AND isnull(YXJGZCBM_LY,'')=isnull(YXJGZCBMX_LY,'')

 GO

 UPDATE YXJGZCBMX SET YXJGZCBMX_FLBH=F_FLBH FROM (  select YXJGZCBMX_IDBAK F_ID,   RIGHT('000000'+CAST(ROW_NUMBER() over(partition by YXJGZCBMX_ID order by YXJGZCBMX_ID desc) AS VARCHAR),4) F_FLBH FROM YXJGZCBMX) LSB WHERE LSB.F_ID=YXJGZCBMX.YXJGZCBMX_IDBAK

 GO
